# skip for a while

sh_stat_xlsx = pd.read_excel(r'P:\Finance\Finance\FP&A\scheduled_1C_reports\Шипменты_группы_осн (XLSX).xlsx')

sh_stat = sh_stat_xlsx.copy()

sh_main_12m_xlsx = pd.read_excel(r'P:\Finance\Finance\FP&A\scheduled_1C_reports\sh_main_12m (XLSX).xlsx')

sh12 = sh_main_12m_xlsx.copy()

# load main data

In [1]:
import pandas as pd

In [2]:
sh_main_3m_xlsx = pd.read_excel(r'P:\Finance\Finance\FP&A\scheduled_1C_reports\sh_main_3m (XLSX).xlsx')

In [3]:
sh3 = sh_main_3m_xlsx.copy()

sh = sh3

In [4]:
if sh.iloc[-1,0] == 'Итого':
    shTot = sh.iloc[-1,].loc['Сумма без НДС']
    print('drop Итого', shTot)
    sh.drop(sh.tail(1).index, inplace=True)

drop Итого 777733858.16

In [5]:
round(sh['Сумма без НДС'].sum(), 2) == shTot

True

In [6]:
sh[['ИНН', 'Заказчик']] = sh['ИНН, Заказчик'].str.split(', ', expand=True, n=1)
sh[['Статья движения денежных средств', 'Договор']] = sh['Статья движения денежных средств, Договор'].str.split(', ', expand=True, n=1)

In [7]:
sh['Дата доставки'] = pd.to_datetime(sh['Дата доставки'], dayfirst=True, errors='coerce')
sh['Дата сбора'] = pd.to_datetime(sh['Дата сбора'], dayfirst=True, errors='coerce')
sh['period'] = sh['Дата доставки'].dt.strftime('%Y-%m')

In [8]:
# пример исправления даты 'на лету'
# sh.loc[3354, 'Дата сбора'] = '23.08.2023'
# sh.loc[85076, 'Дата сбора'] = '29.04.2024'

In [9]:
sh.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29087 entries, 0 to 29086
Data columns (total 51 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Заявки на перевозку                        29087 non-null  object
 1   ИНН, Заказчик                              29087 non-null  object
 2   Статья движения денежных средств, Договор  29087 non-null  object
 3   Грузоотправитель                           29087 non-null  object
 4   Грузополучатель                            29087 non-null  object
 5   Дата доставки                              29087 non-null  datetime64[ns]
 6   Дата сбора                                 29087 non-null  datetime64[ns]
 7   Адрес отправления                          29087 non-null  object
 8   Адрес доставки                             29087 non-null  object
 9   Город отправления                          29087 non-null  object
 10  Город доставки                             29087 non-null  object
 11  Вид перевозки                              29087 non-null  object
 12  Номер авианакладной (HAWB)                 29087 non-null  float64
 13  Вид транспорта                             29087 non-null  object
 14  Организация                                29087 non-null  object
 15  Информация о доставке                      9279 non-null   object
 16  Комментарий для сбора и доставки           16799 non-null  object
 17  Автор                                      29087 non-null  object
 18  Дата создания                              29087 non-null  object
 19  Контактное лицо отправителя                20307 non-null  object
 20  Контактное лицо получателя                 24043 non-null  object
 21  Грузоотправитель партнер                   29087 non-null  object
 22  Грузополучатель партнер                    29087 non-null  object
 23  Дата изменения                             29087 non-null  object
 24  Изменил                                    29087 non-null  object
 25  Ставка НДС                                 29083 non-null  object
 26  Сумма включает НДС                         29087 non-null  object
 27  Дата удаления                              31 non-null     object
 28  Номер заявки клиента                       20820 non-null  object
 29  Дата курса                                 29087 non-null  object
 30  Количество мест                            29039 non-null  float64
 31  Объем, м3                                  0 non-null      float64
 32  Объемный вес, кг                           0 non-null      float64
 33  Оценочная стоимость, руб                   29087 non-null  float64
 34  Масса нетто, кг                            191 non-null    float64
 35  Масса брутто, кг                           29087 non-null  float64
 36  Сумма без НДС                              28943 non-null  float64
 37  Сумма с НДС                                28943 non-null  float64
 38  Оценочная стоимость, USD                   2101 non-null   float64
 39  Оценочная стоимость, EUR                   880 non-null    float64
 40  Оценочная стоимость, GBP                   21 non-null     float64
 41  Оценочная стоимость, CNY                   872 non-null    float64
 42  Оценочная стоимость, CHF                   9 non-null      float64
 43  Оценочная стоимость, RUB                   26466 non-null  float64
 44  Итоговая стоимость USD                     29087 non-null  float64
 45  Группа заявок                              11409 non-null  float64
 46  ИНН                                        29087 non-null  object
 47  Заказчик                                   29087 non-null  object
 48  Статья движения денежных средств           29087 non-null  object
 49  Договор                                    29087 non-null  object
 50  period                                     29087 non-null  object
dtypes: datetime64[ns](2), float64(17), object(32)
memory usage: 11.3+ MB

In [10]:
sh[sh['Сумма без НДС'].isna() == True].count().tail()

ИНН                                 144
Заказчик                            144
Статья движения денежных средств    144
Договор                             144
period                              144
dtype: int64

In [11]:
sh.pivot_table(
    index = 'period',
    values = 'Сумма без НДС',
    aggfunc = 'sum',
    margins = True,
).style.format("{:,.0f}")

In [12]:
city = 'Астрахань'
region = (sh['Город отправления'] == city) & (sh['Город доставки'] == city)

In [13]:
city = 'Волгоград'
region = (sh['Город отправления'] == city) & (sh['Город доставки'] == city)

In [14]:
city = 'Воронеж'
region = (sh['Город отправления'] == city) & (sh['Город доставки'] == city)

In [15]:
city = 'Калуга'
region = (sh['Город отправления'] == city) & (sh['Город доставки'] == city)

In [16]:
sh_reg = sh[region]

In [17]:
sh_reg.pivot_table(
    index = ['Заказчик', 'Вид перевозки'],
    columns = 'period',
    values = 'Сумма без НДС',
    aggfunc = 'sum',
    margins = True,
).style.format("{: .0f}")

In [18]:
sh_reg.pivot_table(
    index = ['Заказчик'],
    columns = 'period',
    values = 'Сумма без НДС',
    aggfunc = 'sum',
    margins=True,
).style.format("{:.0f}")

In [19]:
period = '2025-11'

In [20]:
sh_reg.period.describe()

count          16
unique          7
top       2025-10
freq            3
Name: period, dtype: object

In [21]:
sh_reg[sh_reg['period']==period].pivot_table(
    index = ['Заказчик', 'Вид перевозки', 'Заявки на перевозку',],
    columns = 'period',
    values = 'Сумма без НДС',
    aggfunc = 'sum',
    margins = True,
).drop('All', axis=1).style.format("{: .0f}")

# TMS

## load data

In [22]:
# run_data = pd.read_excel(r'P:\Finance\Finance\FP&A\scheduled_1C_reports\Шипменты_группы_осн (XLSX).xlsx')

In [23]:
run_data = pd.read_excel(r"P:\Finance\Finance\FP&A\scheduled_1C_reports\run (XLSX).xlsx")
run_carrier_data = pd.read_excel(r"P:\Finance\Finance\FP&A\scheduled_1C_reports\run_carrier (XLSX).xlsx")
task_request_data = pd.read_excel(r"P:\Finance\Finance\FP&A\scheduled_1C_reports\task_request (XLSX).xlsx")
request_sh_data = pd.read_excel(r"P:\Finance\Finance\FP&A\scheduled_1C_reports\request_sh (XLSX).xlsx")
run_task_data = pd.read_excel(r"P:\Finance\Finance\FP&A\scheduled_1C_reports\run_task (XLSX).xlsx")

In [24]:
run = run_data.copy()
run_carrier = run_carrier_data.copy()
task_request = task_request_data.copy()
request_sh = request_sh_data.copy()
run_task = run_task_data.copy()

In [25]:
run.head()

,Ссылка,Вид перевозки,Номер рейса,Номер грузовой авианакладной,Вес AWBИтог
0,Рейс 001034355 от 01.12.2023 0:23:39,Ж/д перевозка,NaN,NaN,NaN
1,Рейс 001034356 от 01.12.2023 7:42:21,Автоперевозка (Упрощенный путевой лист),NaN,NaN,NaN
2,Рейс 001034357 от 01.12.2023 7:43:52,Автоперевозка (Упрощенный путевой лист),NaN,NaN,NaN
3,Рейс 001034361 от 01.12.2023 10:14:50,Автоперевозка,NaN,NaN,NaN
4,Рейс 001034362 от 01.12.2023 10:16:09,Автоперевозка,NaN,NaN,NaN

In [26]:
run['Вид перевозки'].describe()

count             73920
unique                6
top       Автоперевозка
freq              25053
Name: Вид перевозки, dtype: object

In [27]:
run['Вид перевозки'].value_counts()

Вид перевозки
Автоперевозка                                    25053
Автоперевозка (Упрощенный путевой лист)          23969
Авиаперевозка                                    13599
Терминальная обработка (операции в аэропорту)    11021
Ж/д перевозка                                      255
Основная перевозка                                  23
Name: count, dtype: int64

In [28]:
run_carrier.head()

,Рейс,Перевозчик,Контрагент,Тип транспортного средства,Транспортное средство
0,Рейс 000005553 от 14.10.2020 11:12:50,NaN,NaN,"от 0,5 до 1",БМД_Моторс 287302 № Т 301 НМ 797
1,Рейс 001031125 от 31.10.2023 18:50:19,NaN,NaN,"от 0,5 до 1",№ А 617 АТ 977 БМД Моторс 287302
2,Рейс 001031127 от 31.10.2023 18:55:58,NaN,NaN,"от 1т до 1,5т",№ Н 967 АН 77 57503А
3,Рейс 001031128 от 31.10.2023 18:57:34,NaN,NaN,"от 0,5 до 1",№ А 562 АТ 977 ГАЗ A32R23
4,Рейс 001031129 от 31.10.2023 18:58:39,NaN,NaN,"от 0,5 до 1",№ Е 484 РЕ 799 Форд Транзит

In [29]:
run_carrier['Контрагент'].describe()

count                        47727
unique                         103
top       СФИНКС СЕКЬЮР ЛОДЖИСТИКС
freq                         21671
Name: Контрагент, dtype: object

In [30]:
run_carrier['Контрагент'].value_counts()

Контрагент
СФИНКС СЕКЬЮР ЛОДЖИСТИКС         21671
Аэрофлот                          3754
Домодедово Карго Сервис Групп     3194
Москва Карго (ГК Шереметьево)     2428
ВНУКОВО-КАРГО                     1886
                                 ...
САВО ООО                             1
ЕТК                                  1
Дельта-Карго Шипинг Сервис           1
Петролеум Аналистс АО                1
ИАТА                                 1
Name: count, Length: 103, dtype: int64

# temp save to pickle

In [31]:
folder_path = "P:\\Finance\\Finance\\FP&A\\scheduled_1C_reports\\"
ext_path = '.pkl'

In [32]:
run.to_pickle(folder_path + 'run' + ext_path)
run_carrier.to_pickle(folder_path + 'run_carrier' + ext_path)
task_request.to_pickle(folder_path + 'task_request' + ext_path)
request_sh.to_pickle(folder_path + 'request_sh' + ext_path)
run_task.to_pickle(folder_path + 'run_task' + ext_path)

In [33]:
sh.to_pickle(folder_path + 'sh' + ext_path)

In [34]:
run = pd.read_pickle(folder_path + 'run' + ext_path)
run_carrier = pd.read_pickle(folder_path + 'run_carrier' + ext_path)
task_request = pd.read_pickle(folder_path + 'task_request' + ext_path)
request_sh = pd.read_pickle(folder_path + 'request_sh' + ext_path)
run_task = pd.read_pickle(folder_path + 'run_task' + ext_path)

In [35]:
sh = pd.read_pickle(folder_path + 'sh' + ext_path)

In [36]:
sh.describe()

,Дата доставки,Дата сбора,Номер авианакладной (HAWB),Количество мест,"Объем, м3","Объемный вес, кг","Оценочная стоимость, руб","Масса нетто, кг","Масса брутто, кг",Сумма без НДС,Сумма с НДС,"Оценочная стоимость, USD","Оценочная стоимость, EUR","Оценочная стоимость, GBP","Оценочная стоимость, CNY","Оценочная стоимость, CHF","Оценочная стоимость, RUB",Итоговая стоимость USD,Группа заявок
count,29087,29087,2.908700e+04,29039.000000,0.0,0.0,2.908700e+04,191.000000,29087.000000,2.894300e+04,2.894300e+04,2.101000e+03,8.800000e+02,21.000000,8.720000e+02,9.000000,2.646600e+04,2.908700e+04,1.140900e+04
mean,2025-09-08 12:48:34.446316288,2025-09-06 19:20:36.960841472,1.000001e+11,3.556803,NaN,NaN,5.919530e+07,347.044387,77.947898,2.687122e+04,3.036669e+04,7.186973e+05,6.238824e+05,135449.761905,3.244263e+06,165108.888889,5.679750e+07,8.007350e+05,1.423255e+05
min,2025-06-01 00:00:00,2025-04-01 00:00:00,1.000001e+11,1.000000,NaN,NaN,1.000000e+00,1.000000,0.010000,1.000000e-02,1.000000e-02,1.000000e+02,8.000000e+01,20.000000,1.000000e+02,5000.000000,1.000000e+00,1.000000e-02,5.000000e+00
25%,2025-07-21 00:00:00,2025-07-18 00:00:00,1.000001e+11,1.000000,NaN,NaN,5.000000e+05,24.219000,1.000000,2.000000e+03,2.400000e+03,1.000000e+05,3.000000e+04,2000.000000,1.000000e+05,10000.000000,5.000000e+05,6.369670e+03,2.111000e+03
50%,2025-09-09 00:00:00,2025-09-08 00:00:00,1.000001e+11,1.000000,NaN,NaN,5.002002e+06,25.089000,3.000000,7.065000e+03,8.478000e+03,2.500000e+05,1.000000e+05,5000.000000,5.000000e+05,50000.000000,3.500000e+06,6.638695e+04,2.208000e+03
75%,2025-10-28 00:00:00,2025-10-27 00:00:00,1.000002e+11,2.000000,NaN,NaN,2.850000e+07,48.739000,14.960000,1.890000e+04,2.268000e+04,5.000000e+05,3.000000e+05,14560.000000,2.000000e+06,100000.000000,2.301378e+07,3.836234e+05,1.515270e+05
max,2026-01-10 00:00:00,2025-12-30 00:00:00,1.000002e+11,4543.000000,NaN,NaN,6.921900e+09,21000.000000,131600.000000,4.389661e+06,5.267593e+06,5.000000e+07,6.900000e+07,1000000.000000,5.000000e+07,619000.000000,6.921900e+09,8.620266e+07,4.542031e+06
std,NaN,NaN,8.576229e+03,31.209954,NaN,NaN,2.402482e+08,1674.323731,1049.201015,1.135029e+05,1.215153e+05,2.714768e+06,3.728400e+06,324673.154551,7.641790e+06,259281.452694,2.337519e+08,3.231504e+06,5.877894e+05

# Payroll

In [2]:
sh_main_3m_xlsx = pd.read_excel(r'P:\Finance\Finance\FP&A\scheduled_1C_reports\sh_main_3m (XLSX).xlsx')

In [41]:
# Укажите путь к файлу и имя нужного листа
file_path = 'C:\OneDrive\Documents\BGS model\Budget\Workings 2025\ЗП_2025.xlsx'
sheet_name = 'data' # или 'Лист1', 'Sheet2' и т.д.

payroll_data = pd.read_excel(file_path, sheet_name=sheet_name)
payroll = payroll_data.copy()

In [42]:
# Теперь df содержит данные только с "НазваниеЛиста"
payroll.head(2)

,Период,Подразделение,Сотрудник,Тип начисления,Value,HC,Подразделение с агентами и исключениям,City Exp,Region,cost_account,Должность,Выбор,Тип.круп.,Тип.инд
0,2023-09-30,Департамент спецавтотранспорта,Алексеев Сергей Сергеевич,Отр.Дн,21.0,0.0,Департамент развития и контроля региональной л...,_Департамент региональных операций,_Москва_ЦО,6000_20 _Indirect,Начальник отдела,False,Дни_Часы,00_Отр.Дн
1,2023-09-30,Департамент спецавтотранспорта,Беликов Сергей Сергеевич,Отр.Дн,21.0,0.0,Департамент спецавтотранспорта,_Москва Спецавтотранспорт,_Москва_33б,6000_25_Admin,Старший механик,False,Дни_Часы,00_Отр.Дн