In [3]:
import pandas as pd

# skip for a while

sh_stat_xlsx = pd.read_excel(r'P:\Finance\Finance\FP&A\scheduled_1C_reports\Шипменты_группы_осн (XLSX).xlsx')

sh_stat = sh_stat_xlsx.copy()

sh_main_12m_xlsx = pd.read_excel(r'P:\Finance\Finance\FP&A\scheduled_1C_reports\sh_main_12m (XLSX).xlsx')

sh12 = sh_main_12m_xlsx.copy()

# load main data

In [2]:
sh_main_3m_xlsx = pd.read_excel(r'P:\Finance\Finance\FP&A\scheduled_1C_reports\sh_main_3m (XLSX).xlsx')

In [3]:
sh3 = sh_main_3m_xlsx.copy()

sh = sh3

In [4]:
if sh.iloc[-1,0] == 'Итого':
    shTot = sh.iloc[-1,].loc['Сумма без НДС']
    print('drop Итого', shTot)
    sh.drop(sh.tail(1).index, inplace=True)

drop Итого 791042530.04

In [5]:
round(sh['Сумма без НДС'].sum(), 2) == shTot

True

In [6]:
sh[['ИНН', 'Заказчик']] = sh['ИНН, Заказчик'].str.split(', ', expand=True, n=1)
sh[['Статья движения денежных средств', 'Договор']] = sh['Статья движения денежных средств, Договор'].str.split(', ', expand=True, n=1)

In [7]:
sh['Дата доставки'] = pd.to_datetime(sh['Дата доставки'], dayfirst=True, errors='coerce')
sh['Дата сбора'] = pd.to_datetime(sh['Дата сбора'], dayfirst=True, errors='coerce')
sh['period'] = sh['Дата доставки'].dt.strftime('%Y-%m')

In [8]:
# пример исправления даты 'на лету'
# sh.loc[3354, 'Дата сбора'] = '23.08.2023'
# sh.loc[85076, 'Дата сбора'] = '29.04.2024'

In [9]:
sh.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29701 entries, 0 to 29700
Data columns (total 51 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Заявки на перевозку                        29701 non-null  object
 1   ИНН, Заказчик                              29701 non-null  object
 2   Статья движения денежных средств, Договор  29701 non-null  object
 3   Грузоотправитель                           29701 non-null  object
 4   Грузополучатель                            29701 non-null  object
 5   Дата доставки                              29701 non-null  datetime64[ns]
 6   Дата сбора                                 29701 non-null  datetime64[ns]
 7   Адрес отправления                          29701 non-null  object
 8   Адрес доставки                             29701 non-null  object
 9   Город отправления                          29701 non-null  object
 10  Город доставки                             29701 non-null  object
 11  Вид перевозки                              29701 non-null  object
 12  Номер авианакладной (HAWB)                 29701 non-null  float64
 13  Вид транспорта                             29701 non-null  object
 14  Организация                                29701 non-null  object
 15  Информация о доставке                      9479 non-null   object
 16  Комментарий для сбора и доставки           17085 non-null  object
 17  Автор                                      29701 non-null  object
 18  Дата создания                              29701 non-null  object
 19  Контактное лицо отправителя                20761 non-null  object
 20  Контактное лицо получателя                 24564 non-null  object
 21  Грузоотправитель партнер                   29701 non-null  object
 22  Грузополучатель партнер                    29701 non-null  object
 23  Дата изменения                             29701 non-null  object
 24  Изменил                                    29701 non-null  object
 25  Ставка НДС                                 29696 non-null  object
 26  Сумма включает НДС                         29701 non-null  object
 27  Дата удаления                              32 non-null     object
 28  Номер заявки клиента                       21231 non-null  object
 29  Дата курса                                 29701 non-null  object
 30  Количество мест                            29653 non-null  float64
 31  Объем, м3                                  0 non-null      float64
 32  Объемный вес, кг                           0 non-null      float64
 33  Оценочная стоимость, руб                   29701 non-null  float64
 34  Масса нетто, кг                            193 non-null    float64
 35  Масса брутто, кг                           29701 non-null  float64
 36  Сумма без НДС                              29556 non-null  float64
 37  Сумма с НДС                                29556 non-null  float64
 38  Оценочная стоимость, USD                   2144 non-null   float64
 39  Оценочная стоимость, EUR                   904 non-null    float64
 40  Оценочная стоимость, GBP                   24 non-null     float64
 41  Оценочная стоимость, CNY                   892 non-null    float64
 42  Оценочная стоимость, CHF                   9 non-null      float64
 43  Оценочная стоимость, RUB                   27024 non-null  float64
 44  Итоговая стоимость USD                     29701 non-null  float64
 45  Группа заявок                              11409 non-null  float64
 46  ИНН                                        29701 non-null  object
 47  Заказчик                                   29701 non-null  object
 48  Статья движения денежных средств           29701 non-null  object
 49  Договор                                    29701 non-null  object
 50  period                                     29701 non-null  object
dtypes: datetime64[ns](2), float64(17), object(32)
memory usage: 11.6+ MB

In [10]:
sh[sh['Сумма без НДС'].isna() == True].count().tail()

ИНН                                 145
Заказчик                            145
Статья движения денежных средств    145
Договор                             145
period                              145
dtype: int64

In [5]:
sh.pivot_table(
    index = 'period',
    values = 'Сумма без НДС',
    aggfunc = 'sum',
    margins = True,
).style.format("{:,.0f}")

In [16]:
city = 'Астрахань'
region = (sh['Город отправления'] == city) & (sh['Город доставки'] == city)

In [21]:
city = 'Волгоград'
region = (sh['Город отправления'] == city) & (sh['Город доставки'] == city)

In [8]:
city = 'Воронеж'
region = (sh['Город отправления'] == city) & (sh['Город доставки'] == city)

In [9]:
city = 'Калуга'
region = (sh['Город отправления'] == city) & (sh['Город доставки'] == city)

In [22]:
sh_reg = sh[region]

In [23]:
sh_reg.pivot_table(
    index = ['Заказчик'],
    columns = 'period',
    values = 'Сумма без НДС',
    aggfunc = 'sum',
    margins=True,
).style.format("{:.0f}")

In [24]:
period = '2025-11'

In [25]:
sh_reg.period.describe()

count         139
unique          7
top       2025-07
freq           25
Name: period, dtype: object

In [27]:
sh_reg[sh_reg['period']==period].pivot_table(
    index = ['Заказчик', 'Вид перевозки',],
    columns = 'period',
    values = 'Сумма без НДС',
    aggfunc = 'sum',
    margins = True,
).drop('All', axis=1).style.format("{:.0f}")

In [26]:
sh_reg[sh_reg['period']==period].pivot_table(
    index = ['Заказчик', 'Вид перевозки', 'Заявки на перевозку',],
    columns = 'period',
    values = 'Сумма без НДС',
    aggfunc = 'sum',
    margins = True,
).drop('All', axis=1).style.format("{:.0f}")

## load data

In [22]:
# run_data = pd.read_excel(r'P:\Finance\Finance\FP&A\scheduled_1C_reports\Шипменты_группы_осн (XLSX).xlsx')

In [23]:
run_data = pd.read_excel(r"P:\Finance\Finance\FP&A\scheduled_1C_reports\run (XLSX).xlsx")
run_carrier_data = pd.read_excel(r"P:\Finance\Finance\FP&A\scheduled_1C_reports\run_carrier (XLSX).xlsx")
task_request_data = pd.read_excel(r"P:\Finance\Finance\FP&A\scheduled_1C_reports\task_request (XLSX).xlsx")
request_sh_data = pd.read_excel(r"P:\Finance\Finance\FP&A\scheduled_1C_reports\request_sh (XLSX).xlsx")
run_task_data = pd.read_excel(r"P:\Finance\Finance\FP&A\scheduled_1C_reports\run_task (XLSX).xlsx")

In [24]:
run = run_data.copy()
run_carrier = run_carrier_data.copy()
task_request = task_request_data.copy()
request_sh = request_sh_data.copy()
run_task = run_task_data.copy()

In [25]:
run.head()

,Ссылка,Вид перевозки,Номер рейса,Номер грузовой авианакладной,Вес AWBИтог
0,Рейс 001034355 от 01.12.2023 0:23:39,Ж/д перевозка,NaN,NaN,NaN
1,Рейс 001034356 от 01.12.2023 7:42:21,Автоперевозка (Упрощенный путевой лист),NaN,NaN,NaN
2,Рейс 001034357 от 01.12.2023 7:43:52,Автоперевозка (Упрощенный путевой лист),NaN,NaN,NaN
3,Рейс 001034361 от 01.12.2023 10:14:50,Автоперевозка,NaN,NaN,NaN
4,Рейс 001034362 от 01.12.2023 10:16:09,Автоперевозка,NaN,NaN,NaN

In [26]:
run['Вид перевозки'].describe()

count             74120
unique                6
top       Автоперевозка
freq              25070
Name: Вид перевозки, dtype: object

In [27]:
run['Вид перевозки'].value_counts()

Вид перевозки
Автоперевозка                                    25070
Автоперевозка (Упрощенный путевой лист)          24124
Авиаперевозка                                    13611
Терминальная обработка (операции в аэропорту)    11036
Ж/д перевозка                                      256
Основная перевозка                                  23
Name: count, dtype: int64

In [28]:
run_carrier.head()

,Рейс,Перевозчик,Контрагент,Тип транспортного средства,Транспортное средство
0,Рейс 000005553 от 14.10.2020 11:12:50,NaN,NaN,"от 0,5 до 1",БМД_Моторс 287302 № Т 301 НМ 797
1,Рейс 001031125 от 31.10.2023 18:50:19,NaN,NaN,"от 0,5 до 1",№ А 617 АТ 977 БМД Моторс 287302
2,Рейс 001031127 от 31.10.2023 18:55:58,NaN,NaN,"от 1т до 1,5т",№ Н 967 АН 77 57503А
3,Рейс 001031128 от 31.10.2023 18:57:34,NaN,NaN,"от 0,5 до 1",№ А 562 АТ 977 ГАЗ A32R23
4,Рейс 001031129 от 31.10.2023 18:58:39,NaN,NaN,"от 0,5 до 1",№ Е 484 РЕ 799 Форд Транзит

In [29]:
run_carrier['Контрагент'].describe()

count                        47772
unique                         103
top       СФИНКС СЕКЬЮР ЛОДЖИСТИКС
freq                         21692
Name: Контрагент, dtype: object

In [30]:
run_carrier['Контрагент'].value_counts()

Контрагент
СФИНКС СЕКЬЮР ЛОДЖИСТИКС         21692
Аэрофлот                          3754
Домодедово Карго Сервис Групп     3197
Москва Карго (ГК Шереметьево)     2430
ВНУКОВО-КАРГО                     1888
                                 ...
САВО ООО                             1
ЕТК                                  1
Дельта-Карго Шипинг Сервис           1
Петролеум Аналистс АО                1
ИАТА                                 1
Name: count, Length: 103, dtype: int64

# Payroll

In [32]:
# Укажите путь к файлу и имя нужного листа
payroll_file_path = 'C:\OneDrive\Documents\BGS model\Budget\Workings 2025\ЗП_2025.xlsx'
payroll_folder_path = 'C:\OneDrive\Documents\BGS model\Budget\Workings 2025\\'
sheet_name = 'data' # или 'Лист1', 'Sheet2' и т.д.

In [33]:
payroll_data = pd.read_excel(payroll_file_path, sheet_name=sheet_name)
payroll = payroll_data.copy()

In [34]:
# Теперь df содержит данные только с "НазваниеЛиста"
payroll.head(2)

,Период,Подразделение,Сотрудник,Тип начисления,Value,HC,Подразделение с агентами и исключениям,City Exp,Region,cost_account,Должность,Выбор,Тип.круп.,Тип.инд
0,2023-09-30,Департамент спецавтотранспорта,Алексеев Сергей Сергеевич,Отр.Дн,21.0,0.0,Департамент развития и контроля региональной л...,_Департамент региональных операций,_Москва_ЦО,6000_20 _Indirect,Начальник отдела,False,Дни_Часы,00_Отр.Дн
1,2023-09-30,Департамент спецавтотранспорта,Беликов Сергей Сергеевич,Отр.Дн,21.0,0.0,Департамент спецавтотранспорта,_Москва Спецавтотранспорт,_Москва_33б,6000_25_Admin,Старший механик,False,Дни_Часы,00_Отр.Дн

# temp save to pickle

In [1]:
folder_path = "P:\\Finance\\Finance\\FP&A\\scheduled_1C_reports\\"
ext_path = '.pkl'

In [36]:
run.to_pickle(folder_path + 'run' + ext_path)
run_carrier.to_pickle(folder_path + 'run_carrier' + ext_path)
task_request.to_pickle(folder_path + 'task_request' + ext_path)
request_sh.to_pickle(folder_path + 'request_sh' + ext_path)
run_task.to_pickle(folder_path + 'run_task' + ext_path)
sh.to_pickle(folder_path + 'sh' + ext_path)

In [37]:
payroll.to_pickle(payroll_folder_path + 'payroll' + ext_path)

# load from pickle
run at request

run = pd.read_pickle(folder_path + 'run' + ext_path)
run_carrier = pd.read_pickle(folder_path + 'run_carrier' + ext_path)
task_request = pd.read_pickle(folder_path + 'task_request' + ext_path)
request_sh = pd.read_pickle(folder_path + 'request_sh' + ext_path)
run_task = pd.read_pickle(folder_path + 'run_task' + ext_path)

In [4]:
sh = pd.read_pickle(folder_path + 'sh' + ext_path)

In [38]:
payroll = pd.read_pickle(payroll_folder_path + 'payroll' + ext_path)

sh.describe()

In [39]:
payroll.describe()

                              Период         Value            HC
count                          33221  3.322100e+04  33221.000000
mean   2024-11-17 10:38:29.262213632  2.163312e+04      0.166371
min              2023-09-30 00:00:00 -3.846150e+04      0.000000
25%              2024-04-30 00:00:00  4.400000e+01      0.000000
50%              2024-11-30 00:00:00  5.129460e+03      0.166667
75%              2025-05-31 00:00:00  2.700000e+04      0.333333
max              2025-11-30 00:00:00  2.686029e+06      1.000000
std                              NaN  5.444062e+04      0.189387

In [40]:
payroll.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33221 entries, 0 to 33220
Data columns (total 14 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Период                                  33221 non-null  datetime64[ns]
 1   Подразделение                           33221 non-null  object
 2   Сотрудник                               33221 non-null  object
 3   Тип начисления                          33221 non-null  object
 4   Value                                   33221 non-null  float64
 5   HC                                      33221 non-null  float64
 6   Подразделение с агентами и исключениям  33221 non-null  object
 7   City Exp                                33221 non-null  object
 8   Region                                  33221 non-null  object
 9   cost_account                            33221 non-null  object
 10  Должность                               33221 non-null  object
 11  Выбор                                   33221 non-null  bool
 12  Тип.круп.                               33221 non-null  object
 13  Тип.инд                                 33221 non-null  object
dtypes: bool(1), datetime64[ns](1), float64(2), object(10)
memory usage: 3.3+ MB