# skip for a while

In [3]:
sh_stat_xlsx = pd.read_excel(r'P:\Finance\Finance\FP&A\scheduled_1C_reports\Шипменты_группы_осн (XLSX).xlsx')

In [4]:
sh_stat = sh_stat_xlsx.copy()

In [2]:
sh_main_12m_xlsx = pd.read_excel(r'P:\Finance\Finance\FP&A\scheduled_1C_reports\sh_main_12m (XLSX).xlsx')

In [21]:
sh12 = sh_main_12m_xlsx.copy()

# load main data

In [1]:
import pandas as pd

In [2]:
sh_main_3m_xlsx = pd.read_excel(r'P:\Finance\Finance\FP&A\scheduled_1C_reports\sh_main_3m (XLSX).xlsx')

In [3]:
sh3 = sh_main_3m_xlsx.copy()

sh = sh3

In [4]:
if sh.iloc[-1,0] == 'Итого':
    shTot = sh.iloc[-1,].loc['Сумма без НДС']
    print('drop Итого', shTot)
    sh.drop(sh.tail(1).index, inplace=True)

drop Итого 773638275.44

In [5]:
round(sh['Сумма без НДС'].sum(), 2) == shTot

True

In [6]:
sh[['ИНН', 'Заказчик']] = sh['ИНН, Заказчик'].str.split(', ', expand=True, n=1)
sh[['Статья движения денежных средств', 'Договор']] = sh['Статья движения денежных средств, Договор'].str.split(', ', expand=True, n=1)

In [21]:
sh['Дата доставки'] = pd.to_datetime(sh['Дата доставки'], dayfirst=True, errors='coerce')
sh['Дата сбора'] = pd.to_datetime(sh['Дата сбора'], dayfirst=True, errors='coerce')
sh['period'] = sh['Дата доставки'].dt.strftime('%Y-%m')

In [8]:
# пример исправления даты 'на лету'
# sh.loc[3354, 'Дата сбора'] = '23.08.2023'
# sh.loc[85076, 'Дата сбора'] = '29.04.2024'

In [22]:
sh.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28896 entries, 0 to 28895
Data columns (total 51 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Заявки на перевозку                        28896 non-null  object
 1   ИНН, Заказчик                              28896 non-null  object
 2   Статья движения денежных средств, Договор  28896 non-null  object
 3   Грузоотправитель                           28896 non-null  object
 4   Грузополучатель                            28896 non-null  object
 5   Дата доставки                              28896 non-null  datetime64[ns]
 6   Дата сбора                                 28896 non-null  datetime64[ns]
 7   Адрес отправления                          28896 non-null  object
 8   Адрес доставки                             28896 non-null  object
 9   Город отправления                          28896 non-null  object
 10  Город доставки                             28896 non-null  object
 11  Вид перевозки                              28896 non-null  object
 12  Номер авианакладной (HAWB)                 28896 non-null  float64
 13  Вид транспорта                             28896 non-null  object
 14  Организация                                28896 non-null  object
 15  Информация о доставке                      9226 non-null   object
 16  Комментарий для сбора и доставки           16682 non-null  object
 17  Автор                                      28896 non-null  object
 18  Дата создания                              28896 non-null  object
 19  Контактное лицо отправителя                20156 non-null  object
 20  Контактное лицо получателя                 23891 non-null  object
 21  Грузоотправитель партнер                   28896 non-null  object
 22  Грузополучатель партнер                    28896 non-null  object
 23  Дата изменения                             28896 non-null  object
 24  Изменил                                    28896 non-null  object
 25  Ставка НДС                                 28892 non-null  object
 26  Сумма включает НДС                         28896 non-null  object
 27  Дата удаления                              30 non-null     object
 28  Номер заявки клиента                       20655 non-null  object
 29  Дата курса                                 28896 non-null  object
 30  Количество мест                            28851 non-null  float64
 31  Объем, м3                                  0 non-null      float64
 32  Объемный вес, кг                           0 non-null      float64
 33  Оценочная стоимость, руб                   28896 non-null  float64
 34  Масса нетто, кг                            190 non-null    float64
 35  Масса брутто, кг                           28896 non-null  float64
 36  Сумма без НДС                              28753 non-null  float64
 37  Сумма с НДС                                28753 non-null  float64
 38  Оценочная стоимость, USD                   2082 non-null   float64
 39  Оценочная стоимость, EUR                   869 non-null    float64
 40  Оценочная стоимость, GBP                   21 non-null     float64
 41  Оценочная стоимость, CNY                   863 non-null    float64
 42  Оценочная стоимость, CHF                   9 non-null      float64
 43  Оценочная стоимость, RUB                   26307 non-null  float64
 44  Итоговая стоимость USD                     28896 non-null  float64
 45  Группа заявок                              11404 non-null  float64
 46  ИНН                                        28896 non-null  object
 47  Заказчик                                   28896 non-null  object
 48  Статья движения денежных средств           28896 non-null  object
 49  Договор                                    28896 non-null  object
 50  period                                     28896 non-null  object
dtypes: datetime64[ns](2), float64(17), object(32)
memory usage: 11.2+ MB

In [9]:
sh[sh['Сумма без НДС'].isna() == True].count().tail()

ИНН                                 143
Заказчик                            143
Статья движения денежных средств    143
Договор                             143
period                              143
dtype: int64

In [10]:
sh.pivot_table(
    index = 'period',
    values = 'Сумма без НДС',
    aggfunc = 'sum',
    margins = True,
).style.format("{:,.0f}")

In [11]:
city = 'Астрахань'
region = (sh['Город отправления'] == city) & (sh['Город доставки'] == city)

In [12]:
city = 'Волгоград'
region = (sh['Город отправления'] == city) & (sh['Город доставки'] == city)

In [14]:
city = 'Воронеж'
region = (sh['Город отправления'] == city) & (sh['Город доставки'] == city)

In [24]:
city = 'Калуга'
region = (sh['Город отправления'] == city) & (sh['Город доставки'] == city)

In [25]:
sh_reg = sh[region]

In [26]:
sh_reg.pivot_table(
    index = ['Заказчик', 'Вид перевозки'],
    columns = 'period',
    values = 'Сумма без НДС',
    aggfunc = 'sum',
    margins = True,
).style.format("{: .0f}")

In [27]:
sh_reg.pivot_table(
    index = ['Заказчик'],
    columns = 'period',
    values = 'Сумма без НДС',
    aggfunc = 'sum',
    margins=True,
).style.format("{:.0f}")

In [29]:
period = '2025-11'

In [32]:
sh_reg.period.describe()

count          16
unique          7
top       2025-10
freq            3
Name: period, dtype: object

In [39]:
sh_reg[sh_reg['period']==period].pivot_table(
    index = ['Заказчик', 'Вид перевозки', 'Заявки на перевозку',],
    columns = 'period',
    values = 'Сумма без НДС',
    aggfunc = 'sum',
    margins = True,
).drop('All', axis=1).style.format("{: .0f}")

# TMS

## load data

In [12]:
# run_data = pd.read_excel(r'P:\Finance\Finance\FP&A\scheduled_1C_reports\Шипменты_группы_осн (XLSX).xlsx')

In [18]:
run_data = pd.read_excel(r"P:\Finance\Finance\FP&A\scheduled_1C_reports\run (XLSX).xlsx")
run_carrier_data = pd.read_excel(r"P:\Finance\Finance\FP&A\scheduled_1C_reports\run_carrier (XLSX).xlsx")
task_request_data = pd.read_excel(r"P:\Finance\Finance\FP&A\scheduled_1C_reports\task_request (XLSX).xlsx")
request_sh_data = pd.read_excel(r"P:\Finance\Finance\FP&A\scheduled_1C_reports\request_sh (XLSX).xlsx")
run_task_data = pd.read_excel(r"P:\Finance\Finance\FP&A\scheduled_1C_reports\run_task (XLSX).xlsx")

In [19]:
run = run_data.copy()
run_carrier = run_carrier_data.copy()
task_request = task_request_data.copy()
request_sh = request_sh_data.copy()
run_task = run_task_data.copy()

In [20]:
run.head()

,Ссылка,Вид перевозки,Номер рейса,Номер грузовой авианакладной,Вес AWBИтог
0,Рейс 001034355 от 01.12.2023 0:23:39,Ж/д перевозка,NaN,NaN,NaN
1,Рейс 001034356 от 01.12.2023 7:42:21,Автоперевозка (Упрощенный путевой лист),NaN,NaN,NaN
2,Рейс 001034357 от 01.12.2023 7:43:52,Автоперевозка (Упрощенный путевой лист),NaN,NaN,NaN
3,Рейс 001034361 от 01.12.2023 10:14:50,Автоперевозка,NaN,NaN,NaN
4,Рейс 001034362 от 01.12.2023 10:16:09,Автоперевозка,NaN,NaN,NaN

In [16]:
run['Вид перевозки'].describe()

count             73323
unique                6
top       Автоперевозка
freq              24922
Name: Вид перевозки, dtype: object

In [17]:
run['Вид перевозки'].value_counts()

Вид перевозки
Автоперевозка                                    24922
Автоперевозка (Упрощенный путевой лист)          23716
Авиаперевозка                                    13473
Терминальная обработка (операции в аэропорту)    10936
Ж/д перевозка                                      253
Основная перевозка                                  23
Name: count, dtype: int64

In [18]:
run_carrier.head()

,Рейс,Перевозчик,Контрагент,Тип транспортного средства,Транспортное средство
0,Рейс 000005553 от 14.10.2020 11:12:50,NaN,NaN,"от 0,5 до 1",БМД_Моторс 287302 № Т 301 НМ 797
1,Рейс 001031125 от 31.10.2023 18:50:19,NaN,NaN,"от 0,5 до 1",№ А 617 АТ 977 БМД Моторс 287302
2,Рейс 001031127 от 31.10.2023 18:55:58,NaN,NaN,"от 1т до 1,5т",№ Н 967 АН 77 57503А
3,Рейс 001031128 от 31.10.2023 18:57:34,NaN,NaN,"от 0,5 до 1",№ А 562 АТ 977 ГАЗ A32R23
4,Рейс 001031129 от 31.10.2023 18:58:39,NaN,NaN,"от 0,5 до 1",№ Е 484 РЕ 799 Форд Транзит

In [19]:
run_carrier['Контрагент'].describe()

count                        47404
unique                         103
top       СФИНКС СЕКЬЮР ЛОДЖИСТИКС
freq                         21569
Name: Контрагент, dtype: object

In [20]:
run_carrier['Контрагент'].value_counts()

Контрагент
СФИНКС СЕКЬЮР ЛОДЖИСТИКС         21569
Аэрофлот                          3709
Домодедово Карго Сервис Групп     3172
Москва Карго (ГК Шереметьево)     2403
ВНУКОВО-КАРГО                     1874
                                 ...
ИАТА                                 1
Арт-Курьер                           1
ФФ Карго Сервис                      1
Лэнд Аэро ООО                        1
СКАЙ ПАРТНЕР ЛОГИСТИКС ООО           1
Name: count, Length: 103, dtype: int64

# temp save to pickle

In [17]:
folder_path = "P:\\Finance\\Finance\\FP&A\\scheduled_1C_reports\\"
ext_path = '.pkl'

In [41]:
run.to_pickle(folder_path + 'run' + ext_path)
run_carrier.to_pickle(folder_path + 'run_carrier' + ext_path)
task_request.to_pickle(folder_path + 'task_request' + ext_path)
request_sh.to_pickle(folder_path + 'request_sh' + ext_path)
run_task.to_pickle(folder_path + 'run_task' + ext_path)

In [18]:
sh.to_pickle(folder_path + 'sh' + ext_path)

In [19]:
run = pd.read_pickle(folder_path + 'run' + ext_path)
run_carrier = pd.read_pickle(folder_path + 'run_carrier' + ext_path)
task_request = pd.read_pickle(folder_path + 'task_request' + ext_path)
request_sh = pd.read_pickle(folder_path + 'request_sh' + ext_path)
run_task = pd.read_pickle(folder_path + 'run_task' + ext_path)

In [20]:
sh = pd.read_pickle(folder_path + 'sh' + ext_path)

In [22]:
sh.describe()

,Дата доставки,Дата сбора,Номер авианакладной (HAWB),Количество мест,"Объем, м3","Объемный вес, кг","Оценочная стоимость, руб","Масса нетто, кг","Масса брутто, кг",Сумма без НДС,Сумма с НДС,"Оценочная стоимость, USD","Оценочная стоимость, EUR","Оценочная стоимость, GBP","Оценочная стоимость, CNY","Оценочная стоимость, CHF","Оценочная стоимость, RUB",Итоговая стоимость USD,Группа заявок
count,25418,25418,2.541800e+04,25378.000000,0.0,0.0,2.541800e+04,177.000000,25418.000000,2.528700e+04,2.528700e+04,1.732000e+03,7.380000e+02,19.000000,7.680000e+02,8.000000,2.326700e+04,2.541800e+04,1.030700e+04
mean,2025-08-27 01:13:06.375796736,2025-08-25 07:36:07.482886144,1.000001e+11,3.535621,NaN,NaN,5.800875e+07,359.125542,79.735954,2.725298e+04,3.078183e+04,5.841854e+05,4.872942e+05,149673.947368,3.191279e+06,183872.500000,5.671792e+07,7.830752e+05,1.573062e+05
min,2025-06-01 00:00:00,2025-04-01 00:00:00,1.000001e+11,1.000000,NaN,NaN,1.000000e+00,1.000000,0.010000,1.000000e-02,1.000000e-02,1.000000e+02,8.000000e+01,20.000000,1.000000e+02,5000.000000,1.000000e+00,1.000000e-02,5.000000e+00
25%,2025-07-15 00:00:00,2025-07-14 00:00:00,1.000001e+11,1.000000,NaN,NaN,5.000000e+05,24.261000,1.000000,2.000000e+03,2.400000e+03,1.000000e+05,3.000000e+04,2807.500000,1.000000e+05,8750.000000,5.000000e+05,6.346540e+03,2.103000e+03
50%,2025-08-27 00:00:00,2025-08-26 00:00:00,1.000001e+11,1.000000,NaN,NaN,5.000000e+06,25.116000,3.000000,7.065000e+03,8.478000e+03,2.500000e+05,1.000000e+05,6000.000000,5.000000e+05,56490.000000,3.500000e+06,6.551356e+04,2.186000e+03
75%,2025-10-08 00:00:00,2025-10-07 00:00:00,1.000002e+11,2.000000,NaN,NaN,2.842588e+07,48.800000,15.000000,1.908772e+04,2.290526e+04,5.000000e+05,3.000000e+05,17280.000000,2.000000e+06,229750.000000,2.337842e+07,3.808541e+05,1.515360e+05
max,2025-12-08 00:00:00,2025-12-04 17:00:00,1.000002e+11,4543.000000,NaN,NaN,6.921900e+09,21000.000000,131600.000000,4.389661e+06,5.267593e+06,3.893600e+07,3.000000e+07,1000000.000000,5.000000e+07,619000.000000,6.921900e+09,7.991074e+07,4.542031e+06
std,NaN,NaN,7.484326e+03,32.653537,NaN,NaN,2.264635e+08,1729.986266,1114.964020,1.133891e+05,1.216622e+05,1.657368e+06,1.893859e+06,338943.514897,7.464385e+06,270572.332645,2.296513e+08,3.027022e+06,6.165355e+05