In [3]:
sh_stat_xlsx = pd.read_excel(r'P:\Finance\Finance\FP&A\scheduled_1C_reports\Шипменты_группы_осн (XLSX).xlsx')

In [4]:
sh_stat = sh_stat_xlsx.copy()

In [8]:
sh_stat.head()

,Заявки на перевозку,Город отправления,Город доставки,Вид перевозки,Заказчик,Договор,Вид транспорта,Номер заявки клиента,Дата,Статья ДДС,"Оценочная стоимость, руб","Масса брутто, кг","Оценочная стоимость, RUB",Итоговая стоимость USD,Сумма без НДС
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Договор.Статья движения денежных средств,NaN,NaN,NaN,NaN,NaN
1,Заявки на перевозку 00753464 от 02.01.2024 18:...,Москва,Москва,Банкоматы,Промсвязьбанк ПАО Москва,11305-12-23-04,Road,NaN,02.01.2024 18:11:47,ИНКАССАЦИЯ,1.0,1.0,1.0,0.01,7500.0
2,Заявки на перевозку 00753465 от 04.01.2024 15:...,Москва,Москва,Банкоматы,Соколовский АО КБ,4223/10-23/ТЦГ,Road,001,04.01.2024 15:40:17,БАНКИ,1.0,1.0,1.0,0.01,2677.5
3,Заявки на перевозку 00753467 от 08.01.2024 14:...,Москва,Москва,Банкоматы,РОСБАНК ПАО,РБ-000830-2022,Road,231676-15,08.01.2024 14:14:19,ИНКАССАЦИЯ,2000000.0,1.0,2000000.0,22299.45,500.0
4,Заявки на перевозку 00753468 от 08.01.2024 14:...,Москва,Москва,Банкоматы,РОСБАНК ПАО,РБ-000830-2022,Road,231757-15,08.01.2024 14:14:19,ИНКАССАЦИЯ,500000.0,1.0,500000.0,5574.86,500.0

In [2]:
sh_main_12m_xlsx = pd.read_excel(r'P:\Finance\Finance\FP&A\scheduled_1C_reports\sh_main_12m (XLSX).xlsx')

In [21]:
sh12 = sh_main_12m_xlsx.copy()

In [1]:
import pandas as pd

In [2]:
sh_main_3m_xlsx = pd.read_excel(r'P:\Finance\Finance\FP&A\scheduled_1C_reports\sh_main_3m (XLSX).xlsx')

In [3]:
sh3 = sh_main_3m_xlsx.copy()

sh = sh3

In [4]:
if sh.iloc[-1,0] == 'Итого':
    shTot = sh.iloc[-1,].loc['Сумма без НДС']
    print('drop Итого', shTot)
    sh.drop(sh.tail(1).index, inplace=True)

drop Итого 689146099.09

In [5]:
sh['Сумма без НДС'].sum() == shTot

False

In [6]:
sh[['ИНН', 'Заказчик']] = sh['ИНН, Заказчик'].str.split(', ', expand=True, n=1)
sh[['Статья движения денежных средств', 'Договор']] = sh['Статья движения денежных средств, Договор'].str.split(', ', expand=True, n=1)

In [7]:
sh.shape

(25418, 50)

In [8]:
sh['Дата доставки'] = pd.to_datetime(sh['Дата доставки'], dayfirst=True, errors='coerce')
sh['Дата сбора'] = pd.to_datetime(sh['Дата сбора'], dayfirst=True, errors='coerce')
sh['period'] = sh['Дата доставки'].dt.strftime('%Y-%m')

In [9]:
# пример исправления даты 'на лету'
# sh.loc[3354, 'Дата сбора'] = '23.08.2023'
# sh.loc[85076, 'Дата сбора'] = '29.04.2024'

In [10]:
sh[sh['Сумма без НДС'].isna() == True].count().tail()

ИНН                                 131
Заказчик                            131
Статья движения денежных средств    131
Договор                             131
period                              131
dtype: int64

In [11]:
sh.pivot_table(
    index = 'period',
    values = 'Сумма без НДС',
    aggfunc = 'sum',
    margins = True,
).style.format("{:,.0f}")

In [47]:
city = 'Астрахань'
region = (sh['Город отправления'] == city) & (sh['Город доставки'] == city)

In [20]:
city = 'Волгоград'
region = (sh['Город отправления'] == city) & (sh['Город доставки'] == city)

In [24]:
city = 'Воронеж'
region = (sh['Город отправления'] == city) & (sh['Город доставки'] == city)

In [32]:
city = 'Калуга'
region = (sh['Город отправления'] == city) & (sh['Город доставки'] == city)

In [33]:
sh_reg = sh[region]

In [34]:
sh_reg.pivot_table(
    index = ['Заказчик', 'Вид перевозки'],
    columns = 'period',
    values = 'Сумма без НДС',
    aggfunc = 'sum',
    margins = True,
).style.format("{: .0f}")

In [35]:
sh_reg.pivot_table(
    index = ['Заказчик'],
    columns = 'period',
    values = 'Сумма без НДС',
    aggfunc = 'sum',
).style.format("{: .0f}")

In [ ]:
import pandas as pd
sh12 = pd.read_pickle('sh12m.pkl')

In [3]:
sh = sh12.copy()

# TMS

## load data

In [3]:
run_data = pd.read_excel(r'P:\Finance\Finance\FP&A\scheduled_1C_reports\Шипменты_группы_осн (XLSX).xlsx')

"P:\Finance\Finance\FP&A\scheduled_1C_reports\task_request (TXT).txt"
"P:\Finance\Finance\FP&A\scheduled_1C_reports\request_sh (TXT).txt"
"P:\Finance\Finance\FP&A\scheduled_1C_reports\run_task (TXT).txt"
"P:\Finance\Finance\FP&A\scheduled_1C_reports\run (TXT).txt"
"P:\Finance\Finance\FP&A\scheduled_1C_reports\run_carrier (TXT).txt"

"P:\Finance\Finance\FP&A\scheduled_1C_reports\run (XLSX).xlsx"
"P:\Finance\Finance\FP&A\scheduled_1C_reports\run_carrier (XLSX).xlsx"
"P:\Finance\Finance\FP&A\scheduled_1C_reports\task_request (XLSX).xlsx"
"P:\Finance\Finance\FP&A\scheduled_1C_reports\request_sh (XLSX).xlsx"
"P:\Finance\Finance\FP&A\scheduled_1C_reports\run_task (XLSX).xlsx"

In [14]:
run_data = pd.read_excel(r"P:\Finance\Finance\FP&A\scheduled_1C_reports\run (XLSX).xlsx")
run_carrier_data = pd.read_excel(r"P:\Finance\Finance\FP&A\scheduled_1C_reports\run_carrier (XLSX).xlsx")
task_request_data = pd.read_excel(r"P:\Finance\Finance\FP&A\scheduled_1C_reports\task_request (XLSX).xlsx")
request_sh_data = pd.read_excel(r"P:\Finance\Finance\FP&A\scheduled_1C_reports\request_sh (XLSX).xlsx")
run_task_data = pd.read_excel(r"P:\Finance\Finance\FP&A\scheduled_1C_reports\run_task (XLSX).xlsx")

In [15]:
run = run_data.copy()
run_carrier = run_carrier_data.copy()
task_request = task_request_data.copy()
request_sh = request_sh_data.copy()
run_task = run_task_data.copy()

In [17]:
run.head()

,Ссылка,Вид перевозки,Номер рейса,Номер грузовой авианакладной,Вес AWBИтог
0,Рейс 001034355 от 01.12.2023 0:23:39,Ж/д перевозка,NaN,NaN,NaN
1,Рейс 001034356 от 01.12.2023 7:42:21,Автоперевозка (Упрощенный путевой лист),NaN,NaN,NaN
2,Рейс 001034357 от 01.12.2023 7:43:52,Автоперевозка (Упрощенный путевой лист),NaN,NaN,NaN
3,Рейс 001034361 от 01.12.2023 10:14:50,Автоперевозка,NaN,NaN,NaN
4,Рейс 001034362 от 01.12.2023 10:16:09,Автоперевозка,NaN,NaN,NaN

In [23]:
run['Вид перевозки'].describe()

count             71774
unique                6
top       Автоперевозка
freq              24580
Name: Вид перевозки, dtype: object

In [24]:
run['Вид перевозки'].value_counts()

Вид перевозки
Автоперевозка                                    24580
Автоперевозка (Упрощенный путевой лист)          23068
Авиаперевозка                                    13157
Терминальная обработка (операции в аэропорту)    10699
Ж/д перевозка                                      249
Основная перевозка                                  21
Name: count, dtype: int64

In [22]:
run_carrier.head()

,Рейс,Перевозчик,Контрагент,Тип транспортного средства,Транспортное средство
0,Рейс 000005553 от 14.10.2020 11:12:50,NaN,NaN,"от 0,5 до 1",БМД_Моторс 287302 № Т 301 НМ 797
1,Рейс 001031125 от 31.10.2023 18:50:19,NaN,NaN,"от 0,5 до 1",№ А 617 АТ 977 БМД Моторс 287302
2,Рейс 001031127 от 31.10.2023 18:55:58,NaN,NaN,"от 1т до 1,5т",№ Н 967 АН 77 57503А
3,Рейс 001031128 от 31.10.2023 18:57:34,NaN,NaN,"от 0,5 до 1",№ А 562 АТ 977 ГАЗ A32R23
4,Рейс 001031129 от 31.10.2023 18:58:39,NaN,NaN,"от 0,5 до 1",№ Е 484 РЕ 799 Форд Транзит

In [27]:
run_carrier['Контрагент'].describe()

count                        46568
unique                         103
top       СФИНКС СЕКЬЮР ЛОДЖИСТИКС
freq                         21295
Name: Контрагент, dtype: object

In [26]:
run_carrier['Контрагент'].value_counts()

Контрагент
СФИНКС СЕКЬЮР ЛОДЖИСТИКС         21295
Аэрофлот                          3621
Домодедово Карго Сервис Групп     3116
Москва Карго (ГК Шереметьево)     2339
ВНУКОВО-КАРГО                     1827
                                 ...
ФФ Карго Сервис                      1
Лэнд Аэро ООО                        1
Аэропорт Братск ПАО                  1
САВО ООО                             1
СКАЙ ПАРТНЕР ЛОГИСТИКС ООО           1
Name: count, Length: 103, dtype: int64

## temp save to pickle

In [40]:
folder_path = "P:\\Finance\\Finance\\FP&A\\scheduled_1C_reports\\"
ext_path = '.pkl'

In [41]:
run.to_pickle(folder_path + 'run' + ext_path)
run_carrier.to_pickle(folder_path + 'run_carrier' + ext_path)
task_request.to_pickle(folder_path + 'task_request' + ext_path)
request_sh.to_pickle(folder_path + 'request_sh' + ext_path)
run_task.to_pickle(folder_path + 'run_task' + ext_path)

In [44]:
run = pd.read_pickle(folder_path + 'run' + ext_path)
run_carrier = pd.read_pickle(folder_path + 'run_carrier' + ext_path)
task_request = pd.read_pickle(folder_path + 'task_request' + ext_path)
request_sh = pd.read_pickle(folder_path + 'request_sh' + ext_path)
run_task = pd.read_pickle(folder_path + 'run_task' + ext_path)

In [47]:
run.describe(include='all')

,Ссылка,Вид перевозки,Номер рейса,Номер грузовой авианакладной,Вес AWBИтог
count,71774,71774,13118,9694,3837.000000
unique,71774,6,638,9507,NaN
top,Рейс 001034355 от 01.12.2023 0:23:39,Автоперевозка,VKO-KJA UT-571,АВТО СФИНКС,NaN
freq,1,24580,588,8,NaN
mean,NaN,NaN,NaN,NaN,191.242421
std,NaN,NaN,NaN,NaN,398.869282
min,NaN,NaN,NaN,NaN,0.250000
25%,NaN,NaN,NaN,NaN,9.600000
50%,NaN,NaN,NaN,NaN,31.000000
75%,NaN,NaN,NaN,NaN,161.000000
max,NaN,NaN,NaN,NaN,4227.000000

In [14]:
run_d = pd.read_excel(r"P:\Finance\Finance\FP&A\scheduled_1C_reports\run (XLSX).xlsx")
run_carrier_data = pd.read_excel(r"P:\Finance\Finance\FP&A\scheduled_1C_reports\run_carrier (XLSX).xlsx")
task_request_data = pd.read_excel(r"P:\Finance\Finance\FP&A\scheduled_1C_reports\task_request (XLSX).xlsx")
request_sh_data = pd.read_excel(r"P:\Finance\Finance\FP&A\scheduled_1C_reports\request_sh (XLSX).xlsx")
run_task_data = pd.read_excel(r"P:\Finance\Finance\FP&A\scheduled_1C_reports\run_task (XLSX).xlsx")