In [1]:
import pandas as pd

In [2]:
sh_main_12m_xlsx = pd.read_excel(r'P:\Finance\Finance\FP&A\scheduled_1C_reports\sh_main_12m (XLSX).xlsx')

In [3]:
sh_main_3m_xlsx = pd.read_excel(r'P:\Finance\Finance\FP&A\scheduled_1C_reports\sh_main_3m (XLSX).xlsx')

In [4]:
sh3 = sh_main_3m_xlsx.copy()

In [19]:
sh = sh3

In [21]:
sh12 = sh_main_12m_xlsx.copy()

In [23]:
sh.shape

(23420, 46)

In [25]:
sh.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23420 entries, 0 to 23419
Data columns (total 46 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Заявки на перевозку                        23420 non-null  object
 1   ИНН, Заказчик                              23419 non-null  object
 2   Статья движения денежных средств, Договор  23419 non-null  object
 3   Грузоотправитель                           23419 non-null  object
 4   Грузополучатель                            23419 non-null  object
 5   Дата доставки                              23419 non-null  object
 6   Дата сбора                                 23419 non-null  object
 7   Адрес отправления                          23419 non-null  object
 8   Адрес доставки                             23419 non-null  object
 9   Город отправления                          23419 non-null  object
 10  Город доставки                             23419 non-null  object
 11  Вид перевозки                              23419 non-null  object
 12  Номер авианакладной (HAWB)                 23419 non-null  float64
 13  Вид транспорта                             23419 non-null  object
 14  Организация                                23419 non-null  object
 15  Информация о доставке                      7497 non-null   object
 16  Комментарий для сбора и доставки           13582 non-null  object
 17  Автор                                      23419 non-null  object
 18  Дата создания                              23419 non-null  object
 19  Контактное лицо отправителя                16264 non-null  object
 20  Контактное лицо получателя                 19228 non-null  object
 21  Грузоотправитель партнер                   23419 non-null  object
 22  Грузополучатель партнер                    23419 non-null  object
 23  Дата изменения                             23419 non-null  object
 24  Изменил                                    23419 non-null  object
 25  Ставка НДС                                 23419 non-null  object
 26  Сумма включает НДС                         23419 non-null  object
 27  Дата удаления                              23 non-null     object
 28  Номер заявки клиента                       16852 non-null  object
 29  Дата курса                                 23419 non-null  object
 30  Количество мест                            23382 non-null  float64
 31  Объем, м3                                  0 non-null      float64
 32  Объемный вес, кг                           0 non-null      float64
 33  Оценочная стоимость, руб                   23420 non-null  float64
 34  Масса нетто, кг                            165 non-null    float64
 35  Масса брутто, кг                           23420 non-null  float64
 36  Сумма без НДС                              23326 non-null  float64
 37  Сумма с НДС                                23326 non-null  float64
 38  Оценочная стоимость, USD                   1577 non-null   float64
 39  Оценочная стоимость, EUR                   686 non-null    float64
 40  Оценочная стоимость, GBP                   18 non-null     float64
 41  Оценочная стоимость, CNY                   692 non-null    float64
 42  Оценочная стоимость, CHF                   5 non-null      float64
 43  Оценочная стоимость, RUB                   21477 non-null  float64
 44  Итоговая стоимость USD                     23420 non-null  float64
 45  Группа заявок                              9666 non-null   float64
dtypes: float64(17), object(29)
memory usage: 8.2+ MB

In [27]:
if sh.iloc[-1,0] == 'Итого':
    print('drop Итого')
    sh.drop(sh.tail(1).index, inplace=True)

drop Итого

In [29]:
sh['Дата доставки'] = pd.to_datetime(sh['Дата доставки'], dayfirst=True, errors='coerce')
sh['Дата сбора'] = pd.to_datetime(sh['Дата сбора'], dayfirst=True, errors='coerce')
sh['period'] = sh['Дата доставки'].dt.strftime('%Y-%m')

In [31]:
sh[sh['Дата сбора'].isna() == True]

Empty DataFrame
Columns: [Заявки на перевозку, ИНН, Заказчик, Статья движения денежных средств, Договор, Грузоотправитель, Грузополучатель, Дата доставки, Дата сбора, Адрес отправления, Адрес доставки, Город отправления, Город доставки, Вид перевозки, Номер авианакладной (HAWB), Вид транспорта, Организация, Информация о доставке, Комментарий для сбора и доставки, Автор, Дата создания, Контактное лицо отправителя, Контактное лицо получателя, Грузоотправитель партнер, Грузополучатель партнер, Дата изменения, Изменил, Ставка НДС, Сумма включает НДС, Дата удаления, Номер заявки клиента, Дата курса, Количество мест, Объем, м3, Объемный вес, кг, Оценочная стоимость, руб, Масса нетто, кг, Масса брутто, кг, Сумма без НДС, Сумма с НДС, Оценочная стоимость, USD, Оценочная стоимость, EUR, Оценочная стоимость, GBP, Оценочная стоимость, CNY, Оценочная стоимость, CHF, Оценочная стоимость, RUB, Итоговая стоимость USD, Группа заявок, period]
Index: []

[0 rows x 47 columns]

In [142]:
# пример исправления даты 'на лету'
# sh.loc[3354, 'Дата сбора'] = '23.08.2023'
# sh.loc[85076, 'Дата сбора'] = '29.04.2024'

In [33]:
sh[sh['Сумма без НДС'].isna() == True].count().tail()

Оценочная стоимость, CHF     0
Оценочная стоимость, RUB    92
Итоговая стоимость USD      94
Группа заявок               53
period                      94
dtype: int64

In [35]:
sh.columns

Index(['Заявки на перевозку', 'ИНН, Заказчик',
       'Статья движения денежных средств, Договор', 'Грузоотправитель',
       'Грузополучатель', 'Дата доставки', 'Дата сбора', 'Адрес отправления',
       'Адрес доставки', 'Город отправления', 'Город доставки',
       'Вид перевозки', 'Номер авианакладной (HAWB)', 'Вид транспорта',
       'Организация', 'Информация о доставке',
       'Комментарий для сбора и доставки', 'Автор', 'Дата создания',
       'Контактное лицо отправителя', 'Контактное лицо получателя',
       'Грузоотправитель партнер', 'Грузополучатель партнер', 'Дата изменения',
       'Изменил', 'Ставка НДС', 'Сумма включает НДС', 'Дата удаления',
       'Номер заявки клиента', 'Дата курса', 'Количество мест', 'Объем, м3',
       'Объемный вес, кг', 'Оценочная стоимость, руб', 'Масса нетто, кг',
       'Масса брутто, кг', 'Сумма без НДС', 'Сумма с НДС',
       'Оценочная стоимость, USD', 'Оценочная стоимость, EUR',
       'Оценочная стоимость, GBP', 'Оценочная стоимость, CNY',
       'Оценочная стоимость, CHF', 'Оценочная стоимость, RUB',
       'Итоговая стоимость USD', 'Группа заявок', 'period'],
      dtype='object')

In [72]:
sh = sh12.copy()

In [56]:
sh = sh3.copy()

In [114]:
sh3 = pd.read_pickle('sh3m.pkl')

In [68]:
sh12 = pd.read_pickle('sh12m.pkl')

In [70]:
sh12.shape, sh.shape

((125713, 46), (23041, 47))

In [126]:
sh3 = sh.copy()

In [128]:
sh3.pivot_table(
    index = 'period',
    values = 'Сумма без НДС',
    aggfunc = 'sum',
).style.format("{:,.0f}")

In [130]:
sh3.to_pickle('sh3m.pkl')

In [144]:
sh12 = sh.copy()

In [146]:
sh12.pivot_table(
    index = 'period',
    values = 'Сумма без НДС',
    aggfunc = 'sum',
).style.format("{:,.0f}")

In [148]:
sh12.to_pickle('sh12m.pkl')

In [2]:
import pandas as pd
sh12 = pd.read_pickle('sh12m.pkl')

In [3]:
sh = sh12.copy()

In [14]:
sh.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125832 entries, 0 to 125831
Data columns (total 47 columns):
 #   Column                                     Non-Null Count   Dtype
---  ------                                     --------------   -----
 0   Заявки на перевозку                        125832 non-null  object
 1   ИНН, Заказчик                              125832 non-null  object
 2   Статья движения денежных средств, Договор  125832 non-null  object
 3   Грузоотправитель                           125832 non-null  object
 4   Грузополучатель                            125832 non-null  object
 5   Дата доставки                              125832 non-null  datetime64[ns]
 6   Дата сбора                                 125832 non-null  datetime64[ns]
 7   Адрес отправления                          125832 non-null  object
 8   Адрес доставки                             125832 non-null  object
 9   Город отправления                          125832 non-null  object
 10  Город доставки                             125832 non-null  object
 11  Вид перевозки                              125832 non-null  object
 12  Номер авианакладной (HAWB)                 125832 non-null  float64
 13  Вид транспорта                             125832 non-null  object
 14  Организация                                125832 non-null  object
 15  Информация о доставке                      35191 non-null   object
 16  Комментарий для сбора и доставки           59860 non-null   object
 17  Автор                                      125832 non-null  object
 18  Дата создания                              125832 non-null  object
 19  Контактное лицо отправителя                81070 non-null   object
 20  Контактное лицо получателя                 88633 non-null   object
 21  Грузоотправитель партнер                   125832 non-null  object
 22  Грузополучатель партнер                    125832 non-null  object
 23  Дата изменения                             125832 non-null  object
 24  Изменил                                    125832 non-null  object
 25  Ставка НДС                                 125793 non-null  object
 26  Сумма включает НДС                         125832 non-null  object
 27  Дата удаления                              114 non-null     object
 28  Номер заявки клиента                       94567 non-null   object
 29  Дата курса                                 125832 non-null  object
 30  Количество мест                            125517 non-null  float64
 31  Объем, м3                                  21 non-null      float64
 32  Объемный вес, кг                           21 non-null      float64
 33  Оценочная стоимость, руб                   125832 non-null  float64
 34  Масса нетто, кг                            281 non-null     float64
 35  Масса брутто, кг                           125832 non-null  float64
 36  Сумма без НДС                              125735 non-null  float64
 37  Сумма с НДС                                125735 non-null  float64
 38  Оценочная стоимость, USD                   6156 non-null    float64
 39  Оценочная стоимость, EUR                   2993 non-null    float64
 40  Оценочная стоимость, GBP                   74 non-null      float64
 41  Оценочная стоимость, CNY                   2346 non-null    float64
 42  Оценочная стоимость, CHF                   45 non-null      float64
 43  Оценочная стоимость, RUB                   117608 non-null  float64
 44  Итоговая стоимость USD                     125797 non-null  float64
 45  Группа заявок                              62919 non-null   float64
 46  period                                     125832 non-null  object
dtypes: datetime64[ns](2), float64(17), object(28)
memory usage: 45.1+ MB

In [12]:
sh.describe()

,Дата доставки,Дата сбора,Номер авианакладной (HAWB),Количество мест,"Объем, м3","Объемный вес, кг","Оценочная стоимость, руб","Масса нетто, кг","Масса брутто, кг",Сумма без НДС,Сумма с НДС,"Оценочная стоимость, USD","Оценочная стоимость, EUR","Оценочная стоимость, GBP","Оценочная стоимость, CNY","Оценочная стоимость, CHF","Оценочная стоимость, RUB",Итоговая стоимость USD,Группа заявок
count,125832,125832,1.258320e+05,125517.000000,21.000000,21.000000,1.258320e+05,281.000000,125832.000000,1.257350e+05,1.257350e+05,6.156000e+03,2.993000e+03,74.000000,2.346000e+03,4.500000e+01,1.176080e+05,1.257970e+05,6.291900e+04
mean,2024-08-28 00:53:02.250619392,2024-08-26 05:04:36.977795840,1.000001e+11,3.684194,0.128919,21.529571,5.045494e+07,253.346758,76.385934,2.103514e+04,2.382792e+04,7.147958e+05,6.080863e+05,64031.689189,3.728893e+06,6.136786e+05,4.785972e+07,6.567319e+05,5.816010e+04
min,2023-07-01 00:00:00,2011-11-01 00:00:00,1.000000e+11,1.000000,0.000800,0.134000,1.000000e+00,0.900000,0.001000,1.000000e-02,1.000000e-02,5.000000e+00,1.000000e+00,10.000000,1.000000e+02,1.000000e+01,1.000000e+00,1.000000e-02,9.000000e+00
25%,2024-02-07 00:00:00,2024-02-06 00:00:00,1.000001e+11,1.000000,0.040500,6.764000,5.000000e+05,1.000000,1.000000,1.350000e+03,1.620000e+03,1.000000e+05,4.000000e+04,950.000000,1.000000e+05,1.600000e+03,5.000000e+05,5.582080e+03,1.463000e+03
50%,2024-08-08 00:00:00,2024-08-06 00:00:00,1.000001e+11,1.000000,0.136125,22.733000,3.000000e+06,24.068000,1.090000,4.550000e+03,5.460000e+03,2.217433e+05,1.000000e+05,4010.000000,6.000000e+05,1.000000e+04,2.350000e+06,3.649433e+04,1.691000e+03
75%,2025-03-31 13:00:00,2025-03-31 00:00:00,1.000001e+11,1.000000,0.136125,22.733000,1.725030e+07,36.078000,11.560750,1.470000e+04,1.764000e+04,5.115000e+05,4.000000e+05,18842.500000,3.000000e+06,6.298000e+04,1.393266e+07,2.335400e+05,1.511830e+05
max,2025-11-28 00:00:00,2025-11-28 00:00:00,1.000002e+11,4582.000000,0.384160,64.155000,9.000000e+09,21000.000000,131600.000000,4.369848e+06,5.243818e+06,6.500000e+07,3.000000e+07,1000000.000000,8.000000e+07,5.546310e+06,9.000000e+09,1.460496e+08,4.542031e+06
std,NaN,NaN,3.712478e+04,30.103280,0.105894,17.684141,2.510710e+08,1469.620219,859.987616,8.127705e+04,8.821195e+04,2.084608e+06,1.811041e+06,189748.649123,8.545130e+06,1.605228e+06,2.504512e+08,3.150160e+06,2.601794e+05