In [1]:
import pandas as pd

In [3]:
sh_stat_xlsx = pd.read_excel(r'P:\Finance\Finance\FP&A\scheduled_1C_reports\Шипменты_группы_осн (XLSX).xlsx')

In [4]:
sh_stat = sh_stat_xlsx.copy()

In [8]:
sh_stat.head()

,Заявки на перевозку,Город отправления,Город доставки,Вид перевозки,Заказчик,Договор,Вид транспорта,Номер заявки клиента,Дата,Статья ДДС,"Оценочная стоимость, руб","Масса брутто, кг","Оценочная стоимость, RUB",Итоговая стоимость USD,Сумма без НДС
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Договор.Статья движения денежных средств,NaN,NaN,NaN,NaN,NaN
1,Заявки на перевозку 00753464 от 02.01.2024 18:...,Москва,Москва,Банкоматы,Промсвязьбанк ПАО Москва,11305-12-23-04,Road,NaN,02.01.2024 18:11:47,ИНКАССАЦИЯ,1.0,1.0,1.0,0.01,7500.0
2,Заявки на перевозку 00753465 от 04.01.2024 15:...,Москва,Москва,Банкоматы,Соколовский АО КБ,4223/10-23/ТЦГ,Road,001,04.01.2024 15:40:17,БАНКИ,1.0,1.0,1.0,0.01,2677.5
3,Заявки на перевозку 00753467 от 08.01.2024 14:...,Москва,Москва,Банкоматы,РОСБАНК ПАО,РБ-000830-2022,Road,231676-15,08.01.2024 14:14:19,ИНКАССАЦИЯ,2000000.0,1.0,2000000.0,22299.45,500.0
4,Заявки на перевозку 00753468 от 08.01.2024 14:...,Москва,Москва,Банкоматы,РОСБАНК ПАО,РБ-000830-2022,Road,231757-15,08.01.2024 14:14:19,ИНКАССАЦИЯ,500000.0,1.0,500000.0,5574.86,500.0

In [2]:
sh_main_12m_xlsx = pd.read_excel(r'P:\Finance\Finance\FP&A\scheduled_1C_reports\sh_main_12m (XLSX).xlsx')

In [21]:
sh12 = sh_main_12m_xlsx.copy()

In [5]:
sh_main_3m_xlsx = pd.read_excel(r'P:\Finance\Finance\FP&A\scheduled_1C_reports\sh_main_3m (XLSX).xlsx')

In [6]:
sh3 = sh_main_3m_xlsx.copy()

sh = sh3

In [5]:
if sh.iloc[-1,0] == 'Итого':
    shTot = sh.iloc[-1,].loc['Сумма без НДС']
    print('drop Итого', shTot)
    sh.drop(sh.tail(1).index, inplace=True)

drop Итого 654174167.83

In [11]:
sh['Сумма без НДС'].sum() == shTot

True

In [7]:
sh[['ИНН', 'Заказчик']] = sh['ИНН, Заказчик'].str.split(', ', expand=True, n=1)
sh[['Статья движения денежных средств', 'Договор']] = sh['Статья движения денежных средств, Договор'].str.split(', ', expand=True, n=1)

In [8]:
sh.shape

(24354, 50)

In [17]:
sh['Дата доставки'] = pd.to_datetime(sh['Дата доставки'], dayfirst=True, errors='coerce')
sh['Дата сбора'] = pd.to_datetime(sh['Дата сбора'], dayfirst=True, errors='coerce')
sh['period'] = sh['Дата доставки'].dt.strftime('%Y-%m')

In [18]:
sh[sh['Дата сбора'].isna() == True]

Empty DataFrame
Columns: [Заявки на перевозку, ИНН, Заказчик, Статья движения денежных средств, Договор, Грузоотправитель, Грузополучатель, Дата доставки, Дата сбора, Адрес отправления, Адрес доставки, Город отправления, Город доставки, Вид перевозки, Номер авианакладной (HAWB), Вид транспорта, Организация, Информация о доставке, Комментарий для сбора и доставки, Автор, Дата создания, Контактное лицо отправителя, Контактное лицо получателя, Грузоотправитель партнер, Грузополучатель партнер, Дата изменения, Изменил, Ставка НДС, Сумма включает НДС, Дата удаления, Номер заявки клиента, Дата курса, Количество мест, Объем, м3, Объемный вес, кг, Оценочная стоимость, руб, Масса нетто, кг, Масса брутто, кг, Сумма без НДС, Сумма с НДС, Оценочная стоимость, USD, Оценочная стоимость, EUR, Оценочная стоимость, GBP, Оценочная стоимость, CNY, Оценочная стоимость, CHF, Оценочная стоимость, RUB, Итоговая стоимость USD, Группа заявок, ИНН, Заказчик, Статья движения денежных средств, Договор, period]
Index: []

[0 rows x 51 columns]

In [142]:
# пример исправления даты 'на лету'
# sh.loc[3354, 'Дата сбора'] = '23.08.2023'
# sh.loc[85076, 'Дата сбора'] = '29.04.2024'

In [17]:
sh[sh['Сумма без НДС'].isna() == True].count().tail()

Оценочная стоимость, CHF     0
Оценочная стоимость, RUB    95
Итоговая стоимость USD      97
Группа заявок               53
period                      97
dtype: int64

In [9]:
sh.columns

Index(['Заявки на перевозку', 'ИНН, Заказчик',
       'Статья движения денежных средств, Договор', 'Грузоотправитель',
       'Грузополучатель', 'Дата доставки', 'Дата сбора', 'Адрес отправления',
       'Адрес доставки', 'Город отправления', 'Город доставки',
       'Вид перевозки', 'Номер авианакладной (HAWB)', 'Вид транспорта',
       'Организация', 'Информация о доставке',
       'Комментарий для сбора и доставки', 'Автор', 'Дата создания',
       'Контактное лицо отправителя', 'Контактное лицо получателя',
       'Грузоотправитель партнер', 'Грузополучатель партнер', 'Дата изменения',
       'Изменил', 'Ставка НДС', 'Сумма включает НДС', 'Дата удаления',
       'Номер заявки клиента', 'Дата курса', 'Количество мест', 'Объем, м3',
       'Объемный вес, кг', 'Оценочная стоимость, руб', 'Масса нетто, кг',
       'Масса брутто, кг', 'Сумма без НДС', 'Сумма с НДС',
       'Оценочная стоимость, USD', 'Оценочная стоимость, EUR',
       'Оценочная стоимость, GBP', 'Оценочная стоимость, CNY',
       'Оценочная стоимость, CHF', 'Оценочная стоимость, RUB',
       'Итоговая стоимость USD', 'Группа заявок', 'ИНН', 'Заказчик',
       'Статья движения денежных средств', 'Договор'],
      dtype='object')

In [10]:
sh['Заказчик'].head()

0        БРИГ- МЕТ ООО
1     Драгмет Приморье
2     Приморье ПАО АКБ
3     Драгмет Приморье
4    Соколовский АО КБ
Name: Заказчик, dtype: object

In [47]:
city = 'Астрахань'
region = (sh['Город отправления'] == city) & (sh['Город доставки'] == city)

In [20]:
city = 'Волгоград'
region = (sh['Город отправления'] == city) & (sh['Город доставки'] == city)

In [24]:
city = 'Воронеж'
region = (sh['Город отправления'] == city) & (sh['Город доставки'] == city)

In [32]:
city = 'Калуга'
region = (sh['Город отправления'] == city) & (sh['Город доставки'] == city)

In [33]:
sh_reg = sh[region]

In [34]:
sh_reg.pivot_table(
    index = ['Заказчик', 'Вид перевозки'],
    columns = 'period',
    values = 'Сумма без НДС',
    aggfunc = 'sum',
    margins = True,
).style.format("{: .0f}")

In [35]:
sh_reg.pivot_table(
    index = ['Заказчик'],
    columns = 'period',
    values = 'Сумма без НДС',
    aggfunc = 'sum',
).style.format("{: .0f}")

In [2]:
import pandas as pd
sh12 = pd.read_pickle('sh12m.pkl')

In [3]:
sh = sh12.copy()

In [33]:
sh.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24196 entries, 0 to 24195
Data columns (total 51 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Заявки на перевозку                        24196 non-null  object
 1   ИНН, Заказчик                              24196 non-null  object
 2   Статья движения денежных средств, Договор  24196 non-null  object
 3   Грузоотправитель                           24196 non-null  object
 4   Грузополучатель                            24196 non-null  object
 5   Дата доставки                              24196 non-null  datetime64[ns]
 6   Дата сбора                                 24196 non-null  datetime64[ns]
 7   Адрес отправления                          24196 non-null  object
 8   Адрес доставки                             24196 non-null  object
 9   Город отправления                          24196 non-null  object
 10  Город доставки                             24196 non-null  object
 11  Вид перевозки                              24196 non-null  object
 12  Номер авианакладной (HAWB)                 24196 non-null  float64
 13  Вид транспорта                             24196 non-null  object
 14  Организация                                24196 non-null  object
 15  Информация о доставке                      7687 non-null   object
 16  Комментарий для сбора и доставки           14045 non-null  object
 17  Автор                                      24196 non-null  object
 18  Дата создания                              24196 non-null  object
 19  Контактное лицо отправителя                16766 non-null  object
 20  Контактное лицо получателя                 19904 non-null  object
 21  Грузоотправитель партнер                   24196 non-null  object
 22  Грузополучатель партнер                    24196 non-null  object
 23  Дата изменения                             24196 non-null  object
 24  Изменил                                    24196 non-null  object
 25  Ставка НДС                                 24196 non-null  object
 26  Сумма включает НДС                         24196 non-null  object
 27  Дата удаления                              24 non-null     object
 28  Номер заявки клиента                       17311 non-null  object
 29  Дата курса                                 24196 non-null  object
 30  Количество мест                            24158 non-null  float64
 31  Объем, м3                                  0 non-null      float64
 32  Объемный вес, кг                           0 non-null      float64
 33  Оценочная стоимость, руб                   24196 non-null  float64
 34  Масса нетто, кг                            171 non-null    float64
 35  Масса брутто, кг                           24196 non-null  float64
 36  Сумма без НДС                              24072 non-null  float64
 37  Сумма с НДС                                24072 non-null  float64
 38  Оценочная стоимость, USD                   1640 non-null   float64
 39  Оценочная стоимость, EUR                   704 non-null    float64
 40  Оценочная стоимость, GBP                   19 non-null     float64
 41  Оценочная стоимость, CNY                   719 non-null    float64
 42  Оценочная стоимость, CHF                   7 non-null      float64
 43  Оценочная стоимость, RUB                   22176 non-null  float64
 44  Итоговая стоимость USD                     24196 non-null  float64
 45  Группа заявок                              9985 non-null   float64
 46  ИНН                                        24196 non-null  object
 47  Заказчик                                   24196 non-null  object
 48  Статья движения денежных средств           24196 non-null  object
 49  Договор                                    24196 non-null  object
 50  period                                     24196 non-null  object
dtypes: datetime64[ns](2), float64(17), object(32)
memory usage: 9.4+ MB