In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from sklearn import tree
from sklearn import model_selection
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error

In [2]:
# работает через direct_url
standart_url = 'https://drive.google.com/file/d/14upz4Y45oImXk52zjZZ62SxM889WIhTp/view?usp=drive_link'
direct_url = 'https://drive.google.com/uc?export=view&id=14upz4Y45oImXk52zjZZ62SxM889WIhTp'

data_load = pd.read_csv(direct_url)

In [3]:
df = data_load.copy()
df.head()

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,W,...,71.0,22.0,1007.7,1007.1,8.0,NaN,16.9,21.8,No,No
1,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,NNW,...,44.0,25.0,1010.6,1007.8,NaN,NaN,17.2,24.3,No,No
2,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,W,...,38.0,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2,No,No
3,2008-12-04,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,SE,...,45.0,16.0,1017.6,1012.8,NaN,NaN,18.1,26.5,No,No
4,2008-12-05,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,ENE,...,82.0,33.0,1010.8,1006.0,7.0,8.0,17.8,29.7,No,No

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145460 entries, 0 to 145459
Data columns (total 23 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Date           145460 non-null  object
 1   Location       145460 non-null  object
 2   MinTemp        143975 non-null  float64
 3   MaxTemp        144199 non-null  float64
 4   Rainfall       142199 non-null  float64
 5   Evaporation    82670 non-null   float64
 6   Sunshine       75625 non-null   float64
 7   WindGustDir    135134 non-null  object
 8   WindGustSpeed  135197 non-null  float64
 9   WindDir9am     134894 non-null  object
 10  WindDir3pm     141232 non-null  object
 11  WindSpeed9am   143693 non-null  float64
 12  WindSpeed3pm   142398 non-null  float64
 13  Humidity9am    142806 non-null  float64
 14  Humidity3pm    140953 non-null  float64
 15  Pressure9am    130395 non-null  float64
 16  Pressure3pm    130432 non-null  float64
 17  Cloud9am       89572 non-null   float64
 18  Cloud3pm       86102 non-null   float64
 19  Temp9am        143693 non-null  float64
 20  Temp3pm        141851 non-null  float64
 21  RainToday      142199 non-null  object
 22  RainTomorrow   142193 non-null  object
dtypes: float64(16), object(7)
memory usage: 25.5+ MB

Данные содержат 23 признака и 145 460 наблюдений. Из этих 23 признаков шесть — категориальные, в одном записана дата, а остальные являются непрерывными числовыми данными.

Примеры числовых признаков: температура, скорость ветра, влажность, облачность, атмосферное давление в разное время суток, количество осадков, испарение, количество часов с солнечной погодой.
Примеры категориальных признаков: местоположение, направление ветра в разное время суток, наличие дождя сегодня или завтра.
Целевой переменной является столбец RainTomorrow. Значение этой переменной мы и будем пытаться предсказать.

Подробная расшифровка всех признаков
Date — дата, в которую зафиксировано наблюдение;
Location — местонахождение метеорологической станции;
MinTemp — минимальная температура (℃);
MaxTemp — максимальная температура (℃);
Rainfall — количество осадков (дождь) за сутки (мм);
Evaporation — количество испарений до 9 утра (мм);
Sunshine — количество часов в сутках, когда светило солнце;
WindGustDir — направление самого сильного порыва ветра за последние 24 часа;
WindGustSpeed — скорость самого сильного порыва ветра за последние 24 часа;
WindDir9am — направление ветра в 9 утра;
WindDir3pm — направление ветра в 3 часа дня;
WindSpeed9am — скорость ветра в 9 часов утра;
WindSpeed3pm — скорость ветра в 3 часа дня;
Humidity9am — влажность в 9 утра;
Humidity3pm — влажность в 3 часа дня;
Pressure9am — атмосферное давление в 9 утра;
Pressure3pm — атмосферное давление в 3 часа дня;
Cloud9am — часть неба, закрытая облаками, в 9 утра;
Cloud3pm — часть неба, закрытая облаками, в 3 часа дня;
Temp9am — температура в 9 утра;
Temp3pm — температура в 3 часа дня;
RainToday — наличие дождя в этот день;
RainTomorrow — наличие дождя на следующий день.

In [5]:
df.isnull().sum().sum()

343248

In [6]:
cols_was = df.shape[1]
cols_was

23

In [7]:
df.isnull().sum() > len(df) * 0.4

Date             False
Location         False
MinTemp          False
MaxTemp          False
Rainfall         False
Evaporation       True
Sunshine          True
WindGustDir      False
WindGustSpeed    False
WindDir9am       False
WindDir3pm       False
WindSpeed9am     False
WindSpeed3pm     False
Humidity9am      False
Humidity3pm      False
Pressure9am      False
Pressure3pm      False
Cloud9am         False
Cloud3pm          True
Temp9am          False
Temp3pm          False
RainToday        False
RainTomorrow     False
dtype: bool

In [8]:
# 1. Рассчитываем процент пропущенных значений для каждого столбца
#    и отфильтровываем столбцы, где этот процент превышает 40% (или 0.4)

threshold = (1 - 0.4) * len(df) # Минимальное количество непропущенных значений для сохранения столбца
df = df.dropna(axis='columns', thresh=threshold)

In [9]:
df.shape

(145460, 20)

**Задание 4.3**

Теперь обработаем признаки RainToday и RainTomorrow таким образом, чтобы вместо yes было значение 1, а вместо no — значение 0. Обратите внимание на то, что в признаках RainToday и RainTomorrow присутствуют пропуски, и их трогать не нужно, они должны остаться пропусками. Поэтому обрабатывайте столбцы таким образом, чтобы не видоизменить пропущенные значения.

Вычислите среднее арифметическое для преобразованного признака RainToday и запишите его в ответ, предварительно округлив до двух знаков после точки-разделителя.

In [10]:
df.columns

Index(['Date', 'Location', 'MinTemp', 'MaxTemp', 'Rainfall', 'WindGustDir',
       'WindGustSpeed', 'WindDir9am', 'WindDir3pm', 'WindSpeed9am',
       'WindSpeed3pm', 'Humidity9am', 'Humidity3pm', 'Pressure9am',
       'Pressure3pm', 'Cloud9am', 'Temp9am', 'Temp3pm', 'RainToday',
       'RainTomorrow'],
      dtype='object')

In [11]:
df['RainToday'].value_counts()

RainToday
No     110319
Yes     31880
Name: count, dtype: int64

In [12]:
df['RainTomorrow'].value_counts()

RainTomorrow
No     110316
Yes     31877
Name: count, dtype: int64

In [13]:
selected_columns = ['RainToday', 'RainTomorrow']

df[selected_columns] = df[selected_columns].replace({'Yes': 1, 'No': 0})

/tmp/ipykernel_461632/2112409512.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[selected_columns] = df[selected_columns].replace({'Yes': 1, 'No': 0})

In [14]:
df['RainToday'].value_counts()

RainToday
0.0    110319
1.0     31880
Name: count, dtype: int64

In [15]:
df['RainTomorrow'].value_counts()

RainTomorrow
0.0    110316
1.0     31877
Name: count, dtype: int64

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145460 entries, 0 to 145459
Data columns (total 20 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Date           145460 non-null  object
 1   Location       145460 non-null  object
 2   MinTemp        143975 non-null  float64
 3   MaxTemp        144199 non-null  float64
 4   Rainfall       142199 non-null  float64
 5   WindGustDir    135134 non-null  object
 6   WindGustSpeed  135197 non-null  float64
 7   WindDir9am     134894 non-null  object
 8   WindDir3pm     141232 non-null  object
 9   WindSpeed9am   143693 non-null  float64
 10  WindSpeed3pm   142398 non-null  float64
 11  Humidity9am    142806 non-null  float64
 12  Humidity3pm    140953 non-null  float64
 13  Pressure9am    130395 non-null  float64
 14  Pressure3pm    130432 non-null  float64
 15  Cloud9am       89572 non-null   float64
 16  Temp9am        143693 non-null  float64
 17  Temp3pm        141851 non-null  float64
 18  RainToday      142199 non-null  float64
 19  RainTomorrow   142193 non-null  float64
dtypes: float64(15), object(5)
memory usage: 22.2+ MB

In [17]:
df.describe()

,MinTemp,MaxTemp,Rainfall,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Temp9am,Temp3pm,RainToday,RainTomorrow
count,143975.000000,144199.000000,142199.000000,135197.000000,143693.000000,142398.000000,142806.000000,140953.000000,130395.00000,130432.000000,89572.000000,143693.000000,141851.00000,142199.000000,142193.000000
mean,12.194034,23.221348,2.360918,40.035230,14.043426,18.662657,68.880831,51.539116,1017.64994,1015.255889,4.447461,16.990631,21.68339,0.224193,0.224181
std,6.398495,7.119049,8.478060,13.607062,8.915375,8.809800,19.029164,20.795902,7.10653,7.037414,2.887159,6.488753,6.93665,0.417051,0.417043
min,-8.500000,-4.800000,0.000000,6.000000,0.000000,0.000000,0.000000,0.000000,980.50000,977.100000,0.000000,-7.200000,-5.40000,0.000000,0.000000
25%,7.600000,17.900000,0.000000,31.000000,7.000000,13.000000,57.000000,37.000000,1012.90000,1010.400000,1.000000,12.300000,16.60000,0.000000,0.000000
50%,12.000000,22.600000,0.000000,39.000000,13.000000,19.000000,70.000000,52.000000,1017.60000,1015.200000,5.000000,16.700000,21.10000,0.000000,0.000000
75%,16.900000,28.200000,0.800000,48.000000,19.000000,24.000000,83.000000,66.000000,1022.40000,1020.000000,7.000000,21.600000,26.40000,0.000000,0.000000
max,33.900000,48.100000,371.000000,135.000000,130.000000,87.000000,100.000000,100.000000,1041.00000,1039.600000,9.000000,40.200000,46.70000,1.000000,1.000000

**Задание 4.4**

Обработайте признак Date таким образом, чтобы выделить в отдельный признак Month (номер месяца). Изначальный признак Date удалите. Определите, какой месяц имеет самую большую часть дождливых дней относительно всех дней месяца. В качестве ответа введите порядковый номер месяца.

In [18]:
df.columns

Index(['Date', 'Location', 'MinTemp', 'MaxTemp', 'Rainfall', 'WindGustDir',
       'WindGustSpeed', 'WindDir9am', 'WindDir3pm', 'WindSpeed9am',
       'WindSpeed3pm', 'Humidity9am', 'Humidity3pm', 'Pressure9am',
       'Pressure3pm', 'Cloud9am', 'Temp9am', 'Temp3pm', 'RainToday',
       'RainTomorrow'],
      dtype='object')

In [19]:
df['Date'] = pd.to_datetime(df['Date'])

In [20]:
df['Date'].describe()

count                           145460
mean     2013-04-04 21:08:51.907053568
min                2007-11-01 00:00:00
25%                2011-01-11 00:00:00
50%                2013-06-02 00:00:00
75%                2015-06-14 00:00:00
max                2017-06-25 00:00:00
Name: Date, dtype: object

In [21]:
# Шаг 2: Извлекаем номер месяца и создаем новый столбец 'Month'
df['Month'] = df['Date'].dt.month

In [22]:
df['Month'].describe()

count    145460.000000
mean          6.399615
std           3.427262
min           1.000000
25%           3.000000
50%           6.000000
75%           9.000000
max          12.000000
Name: Month, dtype: float64

In [23]:
df = df.drop(columns='Date')

In [24]:
df.columns

Index(['Location', 'MinTemp', 'MaxTemp', 'Rainfall', 'WindGustDir',
       'WindGustSpeed', 'WindDir9am', 'WindDir3pm', 'WindSpeed9am',
       'WindSpeed3pm', 'Humidity9am', 'Humidity3pm', 'Pressure9am',
       'Pressure3pm', 'Cloud9am', 'Temp9am', 'Temp3pm', 'RainToday',
       'RainTomorrow', 'Month'],
      dtype='object')

In [25]:
df['Month'].value_counts().sum()

145460

In [26]:
df.groupby('Month')['RainToday'].sum().sort_values() / df['Month'].value_counts().sum()

Month
2     0.014959
12    0.015839
10    0.015956
11    0.016603
1     0.016822
4     0.016850
9     0.017874
3     0.019462
5     0.019944
8     0.020473
7     0.021924
6     0.022460
Name: RainToday, dtype: float64

In [28]:
days_in_month = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]

In [29]:
month_days_rain = df.groupby('Month')['RainToday'].sum()
for i in range(1, 13):
    print(i, month_days_rain[i] / days_in_month[i-1])

1 78.93548387096774
2 77.71428571428571
3 91.3225806451613
4 81.7
5 93.58064516129032
6 108.9
7 102.87096774193549
8 96.06451612903226
9 86.66666666666667
10 74.87096774193549
11 80.5
12 74.3225806451613

In [30]:
df

,Location,MinTemp,MaxTemp,Rainfall,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Temp9am,Temp3pm,RainToday,RainTomorrow,Month
0,Albury,13.4,22.9,0.6,W,44.0,W,WNW,20.0,24.0,71.0,22.0,1007.7,1007.1,8.0,16.9,21.8,0.0,0.0,12
1,Albury,7.4,25.1,0.0,WNW,44.0,NNW,WSW,4.0,22.0,44.0,25.0,1010.6,1007.8,NaN,17.2,24.3,0.0,0.0,12
2,Albury,12.9,25.7,0.0,WSW,46.0,W,WSW,19.0,26.0,38.0,30.0,1007.6,1008.7,NaN,21.0,23.2,0.0,0.0,12
3,Albury,9.2,28.0,0.0,NE,24.0,SE,E,11.0,9.0,45.0,16.0,1017.6,1012.8,NaN,18.1,26.5,0.0,0.0,12
4,Albury,17.5,32.3,1.0,W,41.0,ENE,NW,7.0,20.0,82.0,33.0,1010.8,1006.0,7.0,17.8,29.7,0.0,0.0,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145455,Uluru,2.8,23.4,0.0,E,31.0,SE,ENE,13.0,11.0,51.0,24.0,1024.6,1020.3,NaN,10.1,22.4,0.0,0.0,6
145456,Uluru,3.6,25.3,0.0,NNW,22.0,SE,N,13.0,9.0,56.0,21.0,1023.5,1019.1,NaN,10.9,24.5,0.0,0.0,6
145457,Uluru,5.4,26.9,0.0,N,37.0,SE,WNW,9.0,9.0,53.0,24.0,1021.0,1016.8,NaN,12.5,26.1,0.0,0.0,6
145458,Uluru,7.8,27.0,0.0,SE,28.0,SSE,N,13.0,7.0,51.0,24.0,1019.4,1016.5,3.0,15.1,26.0,0.0,0.0,6
145459,Uluru,14.9,NaN,0.0,NaN,NaN,ESE,ESE,17.0,17.0,62.0,36.0,1020.2,1017.9,8.0,15.0,20.9,0.0,NaN,6

**Задание 4.5**

Обработайте оставшиеся категориальные признаки. С помощью метода get_dummies с настройками по умолчанию создайте dummy-переменные для всех категориальных признаков (их пять), которые есть в данных на этот момент.

Кодировку признаков важно выполнить именно в следующем порядке: categoricals = ['Month', 'Location', 'WindGustDir', 'WindDir9am', 'WindDir3pm']. Это необходимо для того, чтобы ваши дальнейшие ответы сходились с нашим решением, так как алгоритм случайного леса, который мы будем использовать в дальнейшем, чувствителен к порядку столбцов. Аргумент categoricals передаётся в функцию pd.get_dummies() с использованием ключевого слова columns, а именно columns=categoricals.

Сколько теперь признаков в данных, если считать целевую переменную?

In [31]:
categoricals = ['Month', 'Location', 'WindGustDir', 'WindDir9am', 'WindDir3pm']
df = pd.get_dummies(df, columns=categoricals)

In [32]:
df.shape

(145460, 124)

**Задание 4.6**

Осталось совсем немного. Удалите все строки, где есть пропуски. Далее разбейте данные на обучающую и тестовую выборки в соотношении 70/30, в качестве значения параметра random_state возьмите число 31.

Каково среднее значение целевой переменной на тестовой выборке? Ответ округлите до двух знаков после точки-разделителя.

In [35]:
df = df.dropna()

In [36]:
# делим выборку на фичи и таргет
target = 'RainTomorrow'
y = df[target]
X = df.drop(columns=target)

In [37]:
y.describe()

count    78257.000000
mean         0.227302
std          0.419092
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          1.000000
Name: RainTomorrow, dtype: float64

In [38]:
# Формируем обучающую и тестовую выборки
test_size = 0.3
random_state = 31
X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, test_size=test_size, random_state=random_state)
print('Train shape: {}'.format(X_train.shape))
print('Test shape: {}'.format(X_test.shape))

Train shape: (54779, 123)
Test shape: (23478, 123)

In [41]:
y_test.describe()

count    23478.000000
mean         0.227703
std          0.419359
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          1.000000
Name: RainTomorrow, dtype: float64

**Задание 4.7**

Теперь давайте вспомним про бутстреп. Он не понадобится нам для решения этой задачи, но будет полезно реализовать его «вручную».

Сделайте оценку стандартного отклонения для среднего значения минимальной температуры для обучающей выборки (то есть для среднего значения по признаку MinTemp). Для этого сгенерируйте 1000 случайных выборок из наших данных — каждая из них должна быть такого же объёма, как и обучающая выборка. Для генерации выборки используйте np.random.randint(): сгенерируйте необходимое количество индексов и по ним извлеките соответствующие элементы выборки. Случайность фиксируйте с помощью np.random.seed(31).

Для каждой выборки вычислите среднее значение, а после найдите стандартное отклонение для этих значений. Ответ округлите до двух знаков после точки-разделителя.

In [45]:
X_train['MinTemp'].mean()

12.922767848993226

In [51]:
np.random.seed(31)
np.random.randint(X_train.shape[0], size=1000)

array([53970, 26640, 27518, 14946,  3735, 33594,    28, 21756, 53981,
       33372, 12154, 48554, 19246, 16134,   338, 51858,  5886, 22553,
       34411, 34204, 50929, 26250,  1393,  3796, 47226, 11948, 47615,
        2763, 18102, 52579, 50834, 24216,  1639, 52079, 20344, 20127,
       21441, 36970, 38043, 33076,  7023, 22488,  8820, 29242, 22193,
       52993, 37985, 38318, 38988, 35980, 32710, 22135, 38150, 25049,
        6048, 34009, 35706,  5591, 28877, 33729, 20742, 32883, 41320,
       13987, 49290, 36252,  3738, 38377, 19507, 27955, 17064, 28189,
        1157, 36806, 30217, 27012, 30405,  6776, 44340, 47402, 40811,
        5618,  4274, 41914, 38928,  7139, 44894, 46593, 36277, 45387,
       27516,  1426, 25307, 43166, 27708, 29334,   262, 17597, 51348,
       41726,  8815, 18902, 21070,  4123, 26978, 50645, 23212, 15091,
       23195, 37154,  9462, 30622, 52127, 13669,  4903, 38013,  1796,
       46342,  9095, 27423, 25382, 46952, 12035,  7993,  6290,  4000,
       53246, 27105, 47398, 44422, 47340, 47232, 43963, 34507,  8668,
       25471, 47827, 52933, 48338, 20671,    98, 33822, 35578, 20638,
        6723, 15793,  6990, 50571, 11764, 48892, 23293, 47426, 45219,
        5504, 49550, 24087, 16743, 52552, 43638, 26966, 47109, 33216,
       47189, 36177, 28381, 22338,   931, 29853, 18600, 37935, 32655,
       50913, 38229, 13881, 16938, 46896, 40684, 27659, 24151, 22013,
       24589, 51283, 49669,  5252, 13117,  6167,  3726, 53535, 25510,
       47774, 49829, 52011, 42494, 12693,  2835, 52035, 15938, 41265,
       49139, 13122,  3701, 10476, 23347, 36742, 21373, 40302,  1295,
        9669, 13439, 53762, 21612, 21906, 21718, 17689,  5539, 24571,
       18736, 31626,  4019,  4694, 15449, 25453,   464, 28173, 27018,
       16752, 54125, 32699, 31231, 53569, 22307, 35071,  6852, 42508,
       41495, 13874, 16207, 21907, 48146, 22419, 37917,  2974, 34558,
       51520, 52550, 40921, 20755, 24366, 28120, 23685, 46261, 51783,
       22844,  9363, 35733, 38309, 39004,  8777, 35328, 41743, 28135,
        7721, 23196,  5108, 25183, 37930, 28690, 33596, 49479, 50521,
       10004, 37345, 15284, 20231, 48012, 10608, 23773, 11478, 28863,
       20243, 36505, 48261, 36364, 19105, 44907, 48953, 46276, 35077,
       28310,  6075,  5540,  2541, 36099, 46603, 47737, 33456, 45025,
        3557, 31224, 45685, 12248, 18421,  1801, 47493, 47879, 35505,
       17980, 25958,   742,  4145, 48375,  9745, 46534, 46591, 12769,
       12056, 49674,  5230, 50617,  6760, 50994, 28226,  8177, 50088,
       48129, 27999, 51430, 46108, 35769, 11671, 50175, 26042, 52686,
       30686, 12354,  1491, 35613, 53834, 15594, 35482, 43626, 47558,
       53684, 19986, 46997, 32752,  6507, 53422, 41948, 10158, 31491,
       46402, 40436, 13304, 41438, 25606, 24193, 13535,  4683, 28823,
       32109, 38246, 48852, 23601, 28655, 28163, 23424,  4795, 14444,
       32558,  9280, 39462, 23791, 18968, 31466, 14593, 45041, 42323,
       29704, 51437, 12100, 12531,  2013,  8910, 11110, 26170, 44258,
       54130, 26013, 29259,  8583, 26855, 41625, 18294,  3490, 11663,
       35978, 38374, 25137,   985, 36759,  9588, 49086, 10589, 51242,
       49246, 17132, 23022, 29984, 40972, 36010, 15136, 21883, 41683,
       13855,  6125,   971,  2142, 15083, 39712,  9948, 52822,  3213,
       16790, 42050, 41557, 15136, 51481,  6953,   363,  6105,  5056,
       14654, 51657, 48556, 31542,  3923, 21494, 47741,  4550, 40193,
       15066, 52910,  6845, 42978, 11552, 28928, 23467,  1100, 48408,
       11460,   742, 51857, 27102, 48689,  6678, 32595, 12225, 45624,
        7385, 41335, 44228,   409, 36367, 26064, 41232, 17389,  3399,
       18423, 35904, 38350, 53755, 17069, 53766, 31112, 47774, 10643,
       13160, 33199, 47477,  5136, 42659, 13789, 25212, 37752, 21321,
       12288, 37154,  6896, 44037, 42418,  5304, 27845, 21932, 44083,
       32742, 21127, 51552, 26379,  1280, 48100, 12753, 18852, 28995,
        9978, 33034, 53132,   765, 27833, 25462, 20967, 31091, 52826,
       20178, 14809, 16291, 47127, 29669, 45320,  4047, 23218, 11538,
       39060,  7183, 18740, 25577, 18666,  5266, 37273, 41103, 32754,
       29496, 46928, 21358, 48351,  4847, 19718, 52072, 25310, 54169,
       25811, 49847, 35778, 15482, 49398, 15665, 39433, 32513, 41427,
        6789, 27594, 45430, 19007, 38426,  4547, 31342,  5460,  5538,
       21884, 13058, 31615, 14657, 11129, 48213, 15131,  7384, 39331,
       40178, 49818, 37617, 17451, 38267, 24460, 31285, 41366, 28366,
       45386,  1606,  9703,  9822, 43691, 19707, 47723, 20565, 31558,
        1975, 35186, 35627, 47207, 16698, 18671, 29163, 35226, 31985,
       35838,  2092, 27059, 26328, 40379, 29236, 36823, 53327, 33080,
       29044, 53790,  3239,  1934, 31038, 18087, 28689, 18265,  4534,
        9286, 21044,  6081, 51984, 39638, 44313, 42654, 19435, 51810,
       24258, 39367,   605, 13593, 33620, 52073,  7397, 41477, 44520,
       28612, 30238, 51814,  9164, 48956,  6752,   558,   311, 46538,
       28393, 53718, 18631, 54750,  1445, 29431, 37228, 49712, 44140,
       13151, 10395, 36800,  8810, 18237, 24639, 54548, 50713, 15028,
       29401,  7417, 24761, 38321, 52799, 25621, 39009, 34307, 14484,
        5498, 10755, 21090, 47207, 34245, 51040, 35747, 15565, 54341,
       49884,  6714, 45150, 13713, 14232, 37040, 36493,  2700, 35438,
       28197, 48091, 25480, 18682, 25091,  5276, 45129, 19932, 35481,
       21991, 30814, 24642, 36725, 37369, 46829, 39366, 18269, 20525,
         128, 11198,  2844, 12694, 52417,  1510, 41835, 21857, 29940,
       22846, 53622,  7254, 53958, 14990, 41005,  9505, 15921, 36113,
       33756, 26515, 34198, 51574, 44072,  5299, 50307, 30503, 48284,
       23986, 32966, 25707,   892, 35792, 43179,  4130, 38274, 53894,
       13476, 49715, 40547,   536, 45289, 14498, 39233, 27228, 47843,
       49440, 13839, 45126, 44923, 47149, 33546,  2798,  9571, 38393,
       27076, 34981,  5245, 33918, 16091, 29252, 42352, 30353, 45481,
        9308, 28563, 46371, 36036, 10928, 49000, 43972, 51089, 27113,
       36549, 54516,  8986, 37893, 11535, 34470, 21546, 16467, 37790,
        3947, 33906,  5999, 16939, 50065,  2621, 32452, 31665,  2567,
       49508, 39545, 24991, 46820, 26854, 17130, 33716, 19693, 21945,
        5805, 23928, 24273, 17552,  9822, 25796, 34617,    62, 23618,
       16348, 34144, 34490, 46610, 27801,  6610,  4169, 37540, 30620,
       29897, 40242, 14749, 10919, 44144, 31887, 36285,  6496, 16022,
       52383, 22835, 50513, 43729, 41022, 33070,  3622, 16730, 23424,
        5426,  5579,   123, 38574, 52318, 39225, 46753, 40105, 43566,
       18638, 16385,  9863, 34886, 53875, 20975, 22810,  8104, 12358,
       38151, 22605, 41206, 46104, 31811, 10838, 32575,  3369, 37004,
       14764,  2001, 42021,  5238,  5023, 41619, 15285,  5609, 12046,
       39249, 27213,  3682,   917,  7457,  7397, 37073, 22048,  1831,
       28949,   221, 13833, 51242, 35742, 39322,  3604, 21102, 35930,
       24256,  8754,  3385, 12344, 42929, 33260, 40618, 46198, 51879,
       23302, 18572, 10126, 49463, 22957,  1979, 46976,  8591, 39224,
       33047, 11992,  5842, 14180, 54437, 51784, 29318, 13705, 30395,
       23275, 47759, 32495, 46668, 23074, 24320, 26135, 10924, 38904,
       34606, 31148,  8392,  8550,  4547, 30949, 42242, 32143, 33531,
        9332, 17278,  4333, 37422, 17164, 14991,  3537, 14880,  8168,
       31499, 40428, 20070, 35851,  7212, 25722, 48122, 37413, 13084,
        7589, 33903, 44723, 47085,  2828,  1477, 54094, 39916,  5896,
       21093,  4743, 28539,   907, 20569,  2419,  1269, 15929, 33077,
       37472, 42157, 37651,  9802,  2431, 22196, 32703, 45139, 13046,
       17545, 20513, 10401, 47288, 39920, 48792, 16415, 50588, 14666,
       19984, 11305, 20856, 43580, 53363,   213,  8560, 50418, 22120,
       41330])

In [49]:
X_train.shape[0]

54779

In [47]:
help(np.random.randint)

Help on built-in function randint:

randint(...) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype=int)

    Return random integers from `low` (inclusive) to `high` (exclusive).

    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).

    .. note::
        New code should use the `~numpy.random.Generator.integers`
        method of a `~numpy.random.Generator` instance instead;
        please see the :ref:`random-quick-start`.

    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distribution (see above for behavior if ``high=None``).
        If array-like, must contain integer values
    size : int or tuple of ints, optional
        Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
        ``m * n * k`` samples are drawn.  Default is None, in which case a
        single value is returned.
    dtype : dtype, optional
        Desired dtype of the result. Byteorder must be native.
        The default value is int.

        .. versionadded:: 1.11.0

    Returns
    -------
    out : int or ndarray of ints
        `size`-shaped array of random integers from the appropriate
        distribution, or a single such random int if `size` not provided.

    See Also
    --------
    random_integers : similar to `randint`, only for the closed
        interval [`low`, `high`], and 1 is the lowest value if `high` is
        omitted.
    random.Generator.integers: which should be used for new code.

    Examples
    --------
    >>> np.random.randint(2, size=10)
    array([1, 0, 0, 0, 1, 1, 0, 0, 1, 0]) # random
    >>> np.random.randint(1, size=10)
    array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

    Generate a 2 x 4 array of ints between 0 and 4, inclusive:

    >>> np.random.randint(5, size=(2, 4))
    array([[4, 0, 2, 1], # random
           [3, 2, 2, 0]])

    Generate a 1 x 3 array with 3 different upper bounds

    >>> np.random.randint(1, [3, 5, 10])
    array([2, 2, 9]) # random

    Generate a 1 by 3 array with 3 different lower bounds

    >>> np.random.randint([1, 5, 7], 10)
    array([9, 8, 7]) # random

    Generate a 2 by 4 array using broadcasting with dtype of uint8

    >>> np.random.randint([1, 3, 5, 7], [[10], [20]], dtype=np.uint8)
    array([[ 8,  6,  9,  7], # random
           [ 1, 16,  9, 12]], dtype=uint8)