# Домашнее задание

Студента Лысогора А.А.

Математический анализ
69 баллов

# **Задача 1** (14 баллов)

Найдите экстремумы функции:

$
f(x, y, z)=2 x^3+2 x y+2 x z+y^2+z^2+2 y-8 .
$

## Подробное решение:

![частные производные первого порядкка](1_dz_1_1.jpg)

$f'x = 6x^2 + 2y + 2z$

$f'y = 2x + 2y + 2$

$f'z = 2x + 2$

$P_1 = (1,−2,−1)$,
$P_2 = (-\frac{1}{3},-\frac{2}{3},\frac{1}{3})$

![частные производные второго порядка](1_dz_1_2.jpg)

$P_1 = (1,−2,−1)$ - локальный минимум

$P_2 = (-\frac{1}{3},-\frac{2}{3},\frac{1}{3})$ - седловая точка

$
f(x, y, z)=2 x^3+2 x y+2 x z+y^2+z^2+2 y-8
$

$
f(1, -2, -1)=2 \cdot (1)^3+2 \cdot 1 \cdot (-2) + 2 \cdot 1 \cdot (-1) + (-2)^2+(-1)^2+2 \cdot (-2)-8 
= 2 - 4 - 2 + 4 + 1 - 4 - 8 = -11 
$

## Ответ:

$P_1 = (1,−2,−1)$ $-$ локальный минимум (локальный, так как функция может принимать и более минимальные значения при $x$ стремящимся к минус бесконечности.

$f(1, -2, -1)= -11$, значение функции в этой точке

# Задача 2 (25 баллов)

Найдите условные экстремумы функции:

$
f(x, y)=4 x+8 y, y^2-2 x y+5=0
$

Вычислите результат самостоятельно (вручную) и с помощью Python. Сравните результаты.

## Самостоятельно вычисление (вручную):

![условные экстремумы](1_dz_2.jpg)

In [14]:
# сохраним полученные занчения для сравнения
from sympy import *
a, b, w = symbols('a b w' )
solutions_manual = [{a: -3, b: -1, w: -2}]
solutions_manual.append({a: 3, b: 1, w: 2})

In [15]:
solutions_manual

[{a: -3, b: -1, w: -2}, {a: 3, b: 1, w: 2}]

## Вычисление с помощью Python:

In [17]:
from sympy import *
a, b, w = symbols('a b w' )

g = 4*a + 8*b
print('Целевая функция для аргументов a и b :\n f = ', g)

q = b**2 - 2*a*b + 5
print('Функция ограничений: ', q,'= 0')

f = 4*a + 8*b + w * (b**2 - 2*a*b + 5)
print('Функция Лагранжа :\n ', f)

fa = f.diff(a)
print('df/da =', fa,'= 0')

fb = f.diff(b)
print('df/db =', fb,'= 0')

fw = f.diff(w)
print('df/dw =', fw,'= 0')

solutions = solve([fa, fb, fw], (a, b, w), dict=True)
print('Стационарная точка M(x,y)_1:\n',float(solutions[0][a]),',',float(solutions[0][b]))
print('Стационарная точка M(x,y)_2:\n',float(solutions[1][a]),',',float(solutions[1][b]))

Целевая функция для аргументов a и b :
 f =  4*a + 8*b
Функция ограничений:  -2*a*b + b**2 + 5 = 0
Функция Лагранжа :
  4*a + 8*b + w*(-2*a*b + b**2 + 5)
df/da = -2*b*w + 4 = 0
df/db = w*(-2*a + 2*b) + 8 = 0
df/dw = -2*a*b + b**2 + 5 = 0
Стационарная точка M(x,y)_1:
 -3.0 , -1.0
Стационарная точка M(x,y)_2:
 3.0 , 1.0

## Сравнение результатов:

In [19]:
#сравним значения рассчитанные с помощью Python (слева) и расчитанные вручную
print(solutions[0][a] == solutions_manual[0][a])
print(solutions[0][b] == solutions_manual[0][b])
print(solutions[0][w] == solutions_manual[0][w])
print(solutions[1][a] == solutions_manual[1][a])
print(solutions[1][b] == solutions_manual[1][b])
print(solutions[1][w] == solutions_manual[1][w])

True
True
True
True
True
True

**Ответ:** Условные экстремумы функции находятся:
* в точке $(-3, -1)$ - условный минимум, со значением функции в этой точке равным $-20$
* и в точке $(3, 1)$ - условный максимум, значение функции в этой точке $20$.

Значения рассчитаные вручную и с помощью Python - одинаковые.

# **Задача 3** (30 баллов)

Вам предложены данные с информацией о успеваемости студентов:

Независимые переменные:
* Hours Studied: Общее количество часов, потраченных на учебу каждым студентом.
* Previous Scores: Баллы, полученные студентами на предыдущих экзаменах.
* Sleep Hours: Среднее количество часов сна студента в сутки.
* Sample Question Papers Practiced: Количество пробных экзаменационных работ, с которыми студент занимался.
  
Целевая переменная:
* Performance Index: Показатель общей успеваемости каждого студента. Индекс успеваемости отражает академическую успеваемость студента и округляется до ближайшего целого числа. Индекс варьируется от 10 до 100, при этом более высокие значения свидетельствуют о более высокой успеваемости.

Решите задачу линейной регрессии, реализовав градиентный спуск самостоятельно, не используя готовое решение из какой-либо библиотеки.

In [22]:
import numpy as np
import pandas as pd

df = pd.read_csv('Student_Performance.txt')

df

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91.0
1,4,82,No,4,2,65.0
2,8,51,Yes,7,2,45.0
3,5,52,Yes,5,2,36.0
4,7,75,No,8,5,66.0
...,...,...,...,...,...,...
9995,1,49,Yes,4,2,23.0
9996,7,64,Yes,8,5,58.0
9997,6,83,Yes,8,5,74.0
9998,9,97,Yes,7,0,95.0
9999,7,74,No,8,1,64.0

In [23]:
df.describe()

,Hours Studied,Previous Scores,Sleep Hours,Sample Question Papers Practiced,Performance Index
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,4.992900,69.445700,6.530600,4.583300,55.224800
std,2.589309,17.343152,1.695863,2.867348,19.212558
min,1.000000,40.000000,4.000000,0.000000,10.000000
25%,3.000000,54.000000,5.000000,2.000000,40.000000
50%,5.000000,69.000000,7.000000,5.000000,55.000000
75%,7.000000,85.000000,8.000000,7.000000,71.000000
max,9.000000,99.000000,9.000000,9.000000,100.000000

In [24]:
df.isnull().sum()

Hours Studied                       0
Previous Scores                     0
Extracurricular Activities          0
Sleep Hours                         0
Sample Question Papers Practiced    0
Performance Index                   0
dtype: int64

In [25]:
X = df[['Hours Studied', 'Previous Scores', 'Sleep Hours', 'Sample Question Papers Practiced']].values

y = df['Performance Index']
n = len(y)
X = np.append(np.ones((n, 1)), X, axis=1)

y = df['Performance Index'].values.reshape(n, 1)

par = np.zeros((5, 1))

def performance_index(X, y, par):
    y_pred = np.dot(X, par)
    error = (y_pred - y)**2
    perfect = (1/(2*n)) * np.sum(error)

    return perfect


def grad_d(X, y, par, alpha, iterations):
    perf_ind = []
    for i in range(iterations):
        y_pred = np.dot(X, par)
        der = np.dot (X.transpose(), (y_pred - y))/ n
        par -= alpha * der
        perf_ind.append(performance_index(X, y, par))

        if i % 50_000 == 0:
            print(f"iter={i}", par[0], par[1], par[2], par[3], par[4])

    print(f"iter={i}", par[0], par[1], par[2], par[3], par[4])    
    return par, perf_ind

# 0.000384 - максимально возможный шаг, на бОльших значениях начинает вылетать
step = 0.000384

# меньше итераций, более приемлимое время, результат не точный, до первых трёх знаков
# iter = 700_000

# долго считает, но выдаёт результат равный библиотечному
iter = 2_300_000

par, perf_opt = grad_d(X, y, par, step, iter)

iter=0 [0.02120632] [0.11301969] [1.58977582] [0.13909183] [0.09811016]
iter=50000 [-13.41107393] [2.4496453] [0.89597543] [-0.73966622] [-0.08886046]
iter=100000 [-21.47783153] [2.60965933] [0.9441973] [-0.25773934] [0.02370262]
iter=150000 [-26.34733307] [2.70627725] [0.97367992] [0.03320943] [0.09167474]
iter=200000 [-29.28681273] [2.76460078] [0.99147742] [0.20884099] [0.13270619]
iter=250000 [-31.06123269] [2.79980784] [1.0022209] [0.31486116] [0.15747487]
iter=300000 [-32.13236314] [2.82106061] [1.00870622] [0.37886035] [0.17242651]
iter=350000 [-32.77895215] [2.83388987] [1.01262108] [0.41749353] [0.18145209]
iter=400000 [-33.16926628] [2.84163427] [1.0149843] [0.44081448] [0.18690038]
iter=450000 [-33.40487981] [2.84630919] [1.01641085] [0.4548922] [0.19018925]
iter=500000 [-33.54710816] [2.8491312] [1.01727199] [0.46339023] [0.19217458]
iter=550000 [-33.63296445] [2.85083471] [1.01779182] [0.46852008] [0.19337303]
iter=600000 [-33.68479169] [2.85186304] [1.01810562] [0.47161671] [0.19409647]
iter=650000 [-33.71607726] [2.85248379] [1.01829504] [0.473486] [0.19453318]
iter=700000 [-33.73496282] [2.85285851] [1.01840939] [0.4746144] [0.1947968]
iter=750000 [-33.74636311] [2.85308471] [1.01847841] [0.47529556] [0.19495593]
iter=800000 [-33.75324491] [2.85322125] [1.01852008] [0.47570674] [0.19505199]
iter=850000 [-33.75739912] [2.85330368] [1.01854523] [0.47595495] [0.19510998]
iter=900000 [-33.75990681] [2.85335343] [1.01856041] [0.47610478] [0.19514498]
iter=950000 [-33.76142058] [2.85338347] [1.01856958] [0.47619523] [0.19516611]
iter=1000000 [-33.76233436] [2.8534016] [1.01857511] [0.47624983] [0.19517887]
iter=1050000 [-33.76288597] [2.85341255] [1.01857845] [0.47628279] [0.19518657]
iter=1100000 [-33.76321895] [2.85341915] [1.01858047] [0.47630268] [0.19519122]
iter=1150000 [-33.76341996] [2.85342314] [1.01858168] [0.47631469] [0.19519402]
iter=1200000 [-33.76354129] [2.85342555] [1.01858242] [0.47632194] [0.19519572]
iter=1250000 [-33.76361454] [2.853427] [1.01858286] [0.47632632] [0.19519674]
iter=1300000 [-33.76365875] [2.85342788] [1.01858313] [0.47632896] [0.19519736]
iter=1350000 [-33.76368544] [2.85342841] [1.01858329] [0.47633055] [0.19519773]
iter=1400000 [-33.76370155] [2.85342873] [1.01858339] [0.47633152] [0.19519795]
iter=1450000 [-33.76371128] [2.85342892] [1.01858345] [0.4763321] [0.19519809]
iter=1500000 [-33.76371715] [2.85342904] [1.01858348] [0.47633245] [0.19519817]
iter=1550000 [-33.76372069] [2.85342911] [1.01858351] [0.47633266] [0.19519822]
iter=1600000 [-33.76372283] [2.85342915] [1.01858352] [0.47633279] [0.19519825]
iter=1650000 [-33.76372412] [2.85342918] [1.01858353] [0.47633286] [0.19519827]
iter=1700000 [-33.7637249] [2.85342919] [1.01858353] [0.47633291] [0.19519828]
iter=1750000 [-33.76372537] [2.8534292] [1.01858353] [0.47633294] [0.19519829]
iter=1800000 [-33.76372566] [2.85342921] [1.01858354] [0.47633296] [0.19519829]
iter=1850000 [-33.76372583] [2.85342921] [1.01858354] [0.47633297] [0.19519829]
iter=1900000 [-33.76372593] [2.85342921] [1.01858354] [0.47633297] [0.19519829]
iter=1950000 [-33.763726] [2.85342921] [1.01858354] [0.47633298] [0.1951983]
iter=2000000 [-33.76372603] [2.85342921] [1.01858354] [0.47633298] [0.1951983]
iter=2050000 [-33.76372606] [2.85342921] [1.01858354] [0.47633298] [0.1951983]
iter=2100000 [-33.76372607] [2.85342921] [1.01858354] [0.47633298] [0.1951983]
iter=2150000 [-33.76372608] [2.85342921] [1.01858354] [0.47633298] [0.1951983]
iter=2200000 [-33.76372608] [2.85342921] [1.01858354] [0.47633298] [0.1951983]
iter=2250000 [-33.76372609] [2.85342921] [1.01858354] [0.47633298] [0.1951983]
iter=2299999 [-33.76372609] [2.85342921] [1.01858354] [0.47633298] [0.1951983]

Расчитаем и выведем значения из библиотеки scikit-learn (sklearn):

In [27]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X,y)
print(model.coef_)
print(model.intercept_)

[[0.         2.85342921 1.01858354 0.47633298 0.1951983 ]]
[-33.76372609]

**Ответ:** парметры совпадают.

In [29]:
par

array([[-33.76372609],
       [  2.85342921],
       [  1.01858354],
       [  0.47633298],
       [  0.1951983 ]])

In [30]:
import numpy as np
import statsmodels.api as sm
mod = sm.OLS(y, X)
res = mod.fit()
print(res.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.988
Model:                            OLS   Adj. R-squared:                  0.988
Method:                 Least Squares   F-statistic:                 2.147e+05
Date:                Mon, 10 Nov 2025   Prob (F-statistic):               0.00
Time:                        13:45:51   Log-Likelihood:                -21418.
No. Observations:               10000   AIC:                         4.285e+04
Df Residuals:                    9995   BIC:                         4.288e+04
Df Model:                           4
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        -33.7637      0.127   -266.189      0.000     -34.012     -33.515
x1             2.8534      0.008    358.403      0.000       2.838       2.869
x2             1.0186      0.001    857.021      0.000       1.016       1.021
x3             0.4763      0.012     39.193      0.000       0.453       0.500
x4             0.1952      0.007     27.152      0.000       0.181       0.209
==============================================================================
Omnibus:                        1.962   Durbin-Watson:                   2.004
Prob(Omnibus):                  0.375   Jarque-Bera (JB):                1.977
Skew:                           0.009   Prob(JB):                        0.372
Kurtosis:                       3.067   Cond. No.                         445.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.